# Generated by Django 3.2.4 on 2021-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('require', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('colorCode', models.CharField(blank=True, max_length=256, null=True)),
                ('temp', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('TOFD', 'TOFD'), ('CSWIP', 'CSWIP'), ('LRUT', 'LRUT')], max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwiEnrolmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twiCandidateID', models.CharField(blank=True, max_length=1024, null=True)),
                ('eventName', models.CharField(blank=True, max_length=1024, null=True)),
                ('eventDate', models.DateField(blank=True, null=True)),
                ('firstName', models.CharField(blank=True, max_length=1024, null=True)),
                ('middleName', models.CharField(blank=True, max_length=1024, null=True)),
                ('lastName', models.CharField(blank=True, max_length=1024, null=True)),
                ('birthOfDate', models.DateField(blank=True, null=True)),
                ('permanentPrivateAddress', models.CharField(blank=True, max_length=2048, null=True)),
                ('Postcode', models.CharField(blank=True, max_length=1024, null=True)),
                ('CarRegNo', models.CharField(blank=True, max_length=1024, null=True)),
                ('privateTel', models.CharField(blank=True, max_length=1024, null=True)),
                ('emergencyTel', models.CharField(blank=True, max_length=1024, null=True)),
                ('phone', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('correspondenceAddress', models.CharField(blank=True, max_length=2048, null=True)),
                ('invoiceAddress', models.CharField(blank=True, max_length=2048, null=True)),
                ('sponsoringCompanyAndaddress', models.CharField(blank=True, max_length=2048, null=True)),
                ('sponsorPostcode', models.CharField(blank=True, max_length=1024, null=True)),
                ('sponsorContactName', models.CharField(blank=True, max_length=1024, null=True)),
                ('sponsorTel', models.CharField(blank=True, max_length=1024, null=True)),
                ('sponsorFax', models.CharField(blank=True, max_length=1024, null=True)),
                ('sponsorEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('disability', models.BooleanField(blank=True, null=True)),
                ('sponsorStatus', models.BooleanField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=1024, null=True)),
                ('hearAbout', models.CharField(blank=True, max_length=5000, null=True)),
                ('GDPRstatement', models.BooleanField(blank=True, null=True)),
                ('weldingSocietyOrTwi', models.BooleanField(blank=True, null=True)),
                ('bookingRef', models.CharField(blank=True, max_length=1024, null=True)),
                ('examinationType', models.CharField(blank=True, max_length=1024, null=True)),
                ('examinationBody', models.CharField(blank=True, max_length=1024, null=True)),
                ('uploadedForm', models.FileField(blank=True, null=True, upload_to='uploadedForm')),
                ('uploadedSign', models.FileField(blank=True, null=True, upload_to='uploadedForm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('dbName', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fields', models.ManyToManyField(blank=True, null=True, to='forms.Field')),
            ],
        ),
    ]
