# Generated by Django 3.2.4 on 2021-07-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_category_formslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formslist',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='form',
            field=models.ManyToManyField(blank=True, null=True, to='forms.FormsList'),
        ),
    ]
