# Generated by Django 3.2.4 on 2021-07-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20210722_0454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FormsList',
        ),
    ]
