# Generated by Django 3.2.4 on 2021-07-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_rename_formtype_event_formcategory'),
        ('forms', '0004_auto_20210722_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='twienrolmentform',
            name='formCategory',
            field=models.ForeignKey(default=1050896, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='training.tescandidate'),
            preserve_default=False,
        ),
    ]
