# Generated by Django 3.2.4 on 2021-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210709_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
