# Generated by Django 3.2.4 on 2021-07-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_twienrolmentform_formcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twienrolmentform',
            old_name='formCategory',
            new_name='candidate',
        ),
    ]
