# Generated by Django 3.2.4 on 2021-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rename_formcategory_twienrolmentform_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twienrolmentform',
            old_name='weldingSocietyOrTwi',
            new_name='twiEmployee',
        ),
        migrations.AddField(
            model_name='twienrolmentform',
            name='weldingSociety',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
