# Generated by Django 3.2.4 on 2021-07-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20210725_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='twienrolmentform',
            name='uploadedVerifierSign',
            field=models.FileField(blank=True, null=True, upload_to='uploadedForm'),
        ),
    ]
