# Generated by Django 3.2.4 on 2021-07-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_twienrolmentform_uploadedverifiersign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twienrolmentform',
            old_name='examination',
            new_name='CSWIPWeldingexamination',
        ),
    ]
