# Generated by Django 3.2.4 on 2021-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_rename_examination_twienrolmentform_cswipweldingexamination'),
    ]

    operations = [
        migrations.AddField(
            model_name='twienrolmentform',
            name='eventID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
