# Generated by Django 3.2.4 on 2021-07-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_twienrolmentform_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='twienrolmentform',
            name='confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
