# Generated by Django 3.2.4 on 2021-07-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_twienrolmentform_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGAsExperienceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twiCandidateID', models.CharField(blank=True, max_length=1024, null=True)),
                ('eventName', models.CharField(blank=True, max_length=1024, null=True)),
                ('eventDate', models.DateField(blank=True, null=True)),
                ('firstName', models.CharField(blank=True, max_length=1024, null=True)),
                ('middleName', models.CharField(blank=True, max_length=1024, null=True)),
                ('lastName', models.CharField(blank=True, max_length=1024, null=True)),
                ('birthOfDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
