# Generated by Django 3.2.4 on 2021-07-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_rename_formtype_event_formcategory'),
        ('forms', '0013_bgasexperienceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bgasExperienceForm', models.ManyToManyField(blank=True, null=True, to='forms.BGAsExperienceForm')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_event', to='training.event')),
                ('twiEnrolmentForm', models.ManyToManyField(blank=True, null=True, to='forms.TwiEnrolmentForm')),
            ],
        ),
    ]
