# Generated by Django 3.2.4 on 2021-07-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_rename_formtype_event_formcategory'),
        ('forms', '0015_bgasexperienceform_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='formCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_category_training', to='training.category'),
            preserve_default=False,
        ),
    ]
