# Generated by Django 3.2.5 on 2021-08-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_auto_20210727_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='twienrolmentform',
            name='NDTIndustrySector',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
