# Generated by Django 3.2.5 on 2021-08-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_twienrolmentform_ndtindustrysector'),
    ]

    operations = [
        migrations.AddField(
            model_name='twienrolmentform',
            name='plantInspectionLevel1',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twienrolmentform',
            name='plantInspectionLevel2',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
