# Generated by Django 3.2.5 on 2021-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_twienrolmentform_otherexaminationstitlerequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='twienrolmentform',
            name='otherExaminationsTitle',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
