# Generated by Django 3.2.5 on 2021-08-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_auto_20210808_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgasexperienceform',
            name='VerifierPosition',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
