# Generated by Django 3.2.5 on 2021-08-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_candidateprofile_user'),
        ('forms', '0024_bgasexperienceform_verifierposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSL30LogExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(blank=True, max_length=256, null=True)),
                ('fullname', models.CharField(blank=True, max_length=1024, null=True)),
                ('pslNumber', models.CharField(blank=True, max_length=1024, null=True)),
                ('ndtMethod', models.CharField(blank=True, max_length=1024, null=True)),
                ('employingOrganisation', models.CharField(blank=True, max_length=1024, null=True)),
                ('reviewerName', models.CharField(blank=True, max_length=1024, null=True)),
                ('finalEmployerDeclarationName', models.CharField(blank=True, max_length=1024, null=True)),
                ('dateCandidateDeclaration', models.CharField(blank=True, max_length=1024, null=True)),
                ('reviewerDate', models.CharField(blank=True, max_length=1024, null=True)),
                ('dateFrom', models.DateField(blank=True, null=True)),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psl_candidate', to='training.tescandidate')),
            ],
        ),
    ]
