# Generated by Django 3.2.5 on 2021-08-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_auto_20210813_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdtTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techniqueCode', models.CharField(blank=True, max_length=2048, null=True)),
                ('employerComponent', models.CharField(blank=True, max_length=2048, null=True)),
                ('ndtTask', models.CharField(blank=True, max_length=2048, null=True)),
                ('experienceHours', models.CharField(blank=True, max_length=2048, null=True)),
                ('experienceConfirmed', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='psl30logexp',
            name='ndtTechnique',
            field=models.ManyToManyField(blank=True, null=True, to='forms.NdtTechnique'),
        ),
    ]
