# Generated by Django 3.2.5 on 2021-08-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_candidateprofile_user'),
        ('forms', '0028_auto_20210815_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndttechnique',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ndt_technice_candidate', to='training.tescandidate'),
            preserve_default=False,
        ),
    ]
