# Generated by Django 3.2.5 on 2021-08-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_candidateprofile_user'),
        ('forms', '0029_ndttechnique_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_form', to='training.tescandidate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_form', to='training.event')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_form', to='training.product')),
            ],
        ),
    ]
