# Generated by Django 3.2.5 on 2021-08-18 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_candidateprofile_user'),
        ('forms', '0030_formlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlist',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_form', to='training.event'),
        ),
        migrations.AlterField(
            model_name='formlist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_form', to='training.product'),
        ),
    ]
