# Generated by Django 3.2.5 on 2021-08-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_candidateprofile_user'),
        ('forms', '0031_auto_20210818_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSL30InitialForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerAddres', models.CharField(blank=True, max_length=2048, null=True)),
                ('pslCerAddres', models.CharField(blank=True, max_length=2048, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Femail')], max_length=1, null=True)),
                ('pslNumber', models.CharField(blank=True, max_length=1024, null=True)),
                ('birthDay', models.DateField(blank=True, null=True)),
                ('currentEmploymentDetails', models.CharField(blank=True, max_length=2048, null=True)),
                ('currentEmploymentPosition', models.CharField(blank=True, max_length=1024, null=True)),
                ('currentEmploymentStatus', models.CharField(blank=True, max_length=512, null=True)),
                ('preCerTraining', models.CharField(blank=True, max_length=2048, null=True)),
                ('preCerTrainingDate', models.CharField(blank=True, max_length=512, null=True)),
                ('productInductory', models.CharField(blank=True, max_length=512, null=True)),
                ('ndtMethod', models.CharField(blank=True, max_length=512, null=True)),
                ('level', models.CharField(blank=True, max_length=512, null=True)),
                ('level3State', models.CharField(blank=True, max_length=512, null=True)),
                ('basicRadiationSafty', models.BooleanField(blank=True, null=True)),
                ('radiationProtectionSupervisor', models.BooleanField(blank=True, null=True)),
                ('cerCategory', models.CharField(blank=True, max_length=512, null=True)),
                ('preferredExaminationDateVenue', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_event', to='training.event')),
            ],
        ),
    ]
