# Generated by Django 3.2.5 on 2021-08-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_psl30initialform'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl30initialform',
            name='confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psl30logexp',
            name='confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
