# Generated by Django 3.2.5 on 2021-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0036_auto_20210825_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlist',
            name='FormID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
