# Generated by Django 3.2.5 on 2021-09-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_alter_event_formcategory'),
        ('forms', '0038_currentformercertification_experienceclaimed_ndt15aexperienceverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndt15aexperienceverification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ndt', to='training.event'),
        ),
    ]
