# Generated by Django 3.2.5 on 2021-09-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_alter_event_formcategory'),
        ('forms', '0039_alter_ndt15aexperienceverification_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDTCovid19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateID', models.CharField(blank=True, max_length=512, null=True)),
                ('candidateAdress', models.CharField(blank=True, max_length=512, null=True)),
                ('candidateHomePhone', models.CharField(blank=True, max_length=512, null=True)),
                ('fillingDate', models.DateField(blank=True, null=True)),
                ('confirmCase1', models.BooleanField(blank=True, null=True)),
                ('confirmCase2', models.BooleanField(blank=True, null=True)),
                ('confirmCase3', models.BooleanField(blank=True, null=True)),
                ('confirmCase4', models.BooleanField(blank=True, null=True)),
                ('confirmCase5', models.BooleanField(blank=True, null=True)),
                ('confirmCase6', models.BooleanField(blank=True, null=True)),
                ('medicalTravelCase1', models.BooleanField(blank=True, null=True)),
                ('medicalHistory', models.CharField(blank=True, max_length=512, null=True)),
                ('medicalTravelCase2', models.BooleanField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=512, null=True)),
                ('medicalTravelCase3', models.BooleanField(blank=True, null=True)),
                ('medicalTravelCase4', models.BooleanField(blank=True, null=True)),
                ('afterEventDate', models.DateField(blank=True, null=True)),
                ('confirmation', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_ndt_covid19', to='training.tescandidate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ndt_covid19', to='training.category')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ndt_covid19', to='training.event')),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideline_ndt_covid19', to='training.formslist')),
            ],
        ),
    ]
