# Generated by Django 3.2.5 on 2021-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0042_auto_20210917_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl57b',
            name='NDTLevel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='NDTMethod',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='candidatePosition',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='categoriesOfCertification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='currentEmploymentDetails',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='employmentStatus',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='examinationType',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='ifLevel3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='iroductsIndustrySector',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='preferredExaminationDateVenu',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='recertification',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
