# Generated by Django 3.2.5 on 2021-09-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0043_auto_20210918_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psl57b',
            old_name='pslNumber',
            new_name='accommodation',
        ),
        migrations.AddField(
            model_name='psl57b',
            name='Debit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='NameOnCard',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='addressCreditCardHolder',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='cardNumber',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='cheque',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='companyOrderReference',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='creditCardPayment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='issueExpiryDates',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='nameAddressInvoice',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='nameResponsible',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='pclNumber',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='psl57b',
            name='securityCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
