# Generated by Django 3.2.5 on 2021-09-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0044_auto_20210920_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psl57b',
            old_name='Debit',
            new_name='debit',
        ),
    ]
