# Generated by Django 3.2.5 on 2021-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0046_emphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
