# Generated by Django 3.2.5 on 2021-10-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_alter_event_formcategory'),
        ('forms', '0051_auto_20211002_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.CreateModel(
            name='TesLecFeedbackFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturerName', models.CharField(blank=True, max_length=512, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('knowledge', models.IntegerField(blank=True, null=True)),
                ('knowledgeComment', models.CharField(blank=True, max_length=2048, null=True)),
                ('teachingMethod', models.IntegerField(blank=True, null=True)),
                ('teachingMethodComment', models.CharField(blank=True, max_length=2048, null=True)),
                ('abilityToAnswer', models.IntegerField(blank=True, null=True)),
                ('abilityToAnswerComment', models.CharField(blank=True, max_length=2048, null=True)),
                ('confirmation', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_form_candidate', to='training.tescandidate')),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_form_event', to='training.event')),
            ],
        ),
    ]
