# Generated by Django 3.2.5 on 2021-10-08 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_alter_event_formcategory'),
        ('forms', '0054_auto_20211004_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.CreateModel(
            name='TwiTrainingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=2048, null=True)),
                ('venue', models.CharField(blank=True, max_length=2048, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('lecturerName', models.CharField(blank=True, max_length=2048, null=True)),
                ('programme', models.CharField(blank=True, max_length=2048, null=True)),
                ('bookingProcess', models.CharField(blank=True, max_length=2048, null=True)),
                ('joiningInstructions', models.CharField(blank=True, max_length=2048, null=True)),
                ('trainingEnvironment', models.CharField(blank=True, max_length=2048, null=True)),
                ('objectivesCourse', models.CharField(blank=True, max_length=2048, null=True)),
                ('tutorLecturer', models.CharField(blank=True, max_length=2048, null=True)),
                ('principlesExplained', models.CharField(blank=True, max_length=2048, null=True)),
                ('questionsAnswered', models.CharField(blank=True, max_length=2048, null=True)),
                ('confirmation', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twi_training_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twi_training_event', to='training.event')),
            ],
        ),
    ]
