# Generated by Django 3.2.5 on 2021-10-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_alter_event_formcategory'),
        ('forms', '0055_auto_20211008_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.CreateModel(
            name='TwiExamFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=2048, null=True)),
                ('venue', models.CharField(blank=True, max_length=2048, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=2048, null=True)),
                ('programme', models.CharField(blank=True, max_length=2048, null=True)),
                ('administrativeStaff', models.CharField(blank=True, max_length=2048, null=True)),
                ('examinationRoom', models.CharField(blank=True, max_length=2048, null=True)),
                ('feltComfortable', models.CharField(blank=True, max_length=2048, null=True)),
                ('explanationInvigilator', models.CharField(blank=True, max_length=2048, null=True)),
                ('writtenExamination', models.CharField(blank=True, max_length=2048, null=True)),
                ('courseContent', models.CharField(blank=True, max_length=2048, null=True)),
                ('equipment', models.CharField(blank=True, max_length=2048, null=True)),
                ('samples', models.CharField(blank=True, max_length=2048, null=True)),
                ('reflection', models.CharField(blank=True, max_length=2048, null=True)),
                ('practicalSamples', models.CharField(blank=True, max_length=2048, null=True)),
                ('recommend', models.CharField(blank=True, max_length=2048, null=True)),
                ('comparisonTo', models.CharField(blank=True, max_length=2048, null=True)),
                ('afterYourExperience', models.CharField(blank=True, max_length=2048, null=True)),
                ('catering', models.CharField(blank=True, max_length=2048, null=True)),
                ('howWeDid', models.CharField(blank=True, max_length=4092, null=True)),
                ('candidateOpinion', models.CharField(blank=True, max_length=4092, null=True)),
                ('confirmation', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twi_examg_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twi_texam_event', to='training.event')),
            ],
        ),
    ]
