# Generated by Django 3.2.5 on 2021-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0068_auto_20211020_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
