# Generated by Django 3.2.5 on 2021-10-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0070_auto_20211026_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
