# Generated by Django 3.2.5 on 2021-11-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0089_auto_20211101_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='ACFM',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='appreciationAdvancedNDTmethods',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='appreciationBasicNDTMethod',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='atmosphere',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='audience',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='automatedUltrasonicTesting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='cathodicProtection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='digitalComputedRadiography',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='eddyCurrentTesting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='equipment',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='expectations',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='howWeDid',
            field=models.CharField(blank=True, max_length=9042, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='magneticTesting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='notes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='overallQuality',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='penetrantTesting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='phasedArrayUltrasonic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='practicalSessions',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='pulsedEddyCurrent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='timeFlightDiffraction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='ultrasonicTesting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psl57a',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
