# Generated by Django 3.2.5 on 2021-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0093_auto_20211204_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psl57a',
            name='dateOfCourse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psl57a',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
