# Generated by Django 3.2.5 on 2021-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0094_auto_20211204_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='IIWDiploma',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='introASME',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='introErupeanStandard',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='introNDT',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='paitingInspector',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='partialWelder',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='plantInspector',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='radioIntro',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='radioTesting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='reviewAsmeXI',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='seniorWeldingInspection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='siteCoating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='underWater',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='visualWeldingInspection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='weldingInspection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='weldingInspector',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitrainingfeedback',
            name='weldingQuality',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psl57a',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.AlterField(
            model_name='psl57a',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
