# Generated by Django 3.2.5 on 2021-12-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0095_auto_20211206_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesattcandidate',
            name='dayOneSec5',
        ),
        migrations.RemoveField(
            model_name='tesattcandidate',
            name='dayThreeSec5',
        ),
        migrations.RemoveField(
            model_name='tesattcandidate',
            name='dayTwoSec5',
        ),
        migrations.AlterField(
            model_name='psl57a',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
