# Generated by Django 3.2.5 on 2021-12-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0042_auto_20211015_0816'),
        ('forms', '0096_auto_20211208_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='category_att_train', to='training.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='event',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='event_att_train', to='training.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='guideline',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='guideline_att_train', to='training.formslist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psl57a',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
