# Generated by Django 3.2.5 on 2022-01-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0112_auto_20220113_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl57a',
            name='ndtOther',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='psl57a',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
        migrations.AlterField(
            model_name='psl57b',
            name='emphistory',
            field=models.ManyToManyField(blank=True, null=True, to='forms.empHistory'),
        ),
    ]
