# Generated by Django 4.0.1 on 2022-02-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0062_event_end_date'),
        ('forms', '0122_auto_20220124_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=256, null=True)),
                ('internal_link', models.CharField(blank=True, max_length=256, null=True)),
                ('generated', models.BooleanField(blank=True, null=True)),
                ('sent', models.BooleanField(blank=True, null=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('confirmed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_forms', to='training.tescandidate')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_forms', to='training.category')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_forms', to='training.event')),
            ],
        ),
    ]
