# Generated by Django 4.0.1 on 2022-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0123_candidateforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateforms',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidateforms',
            name='generated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidateforms',
            name='sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidateforms',
            name='submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
