# Generated by Django 4.0.1 on 2022-02-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0062_event_end_date'),
        ('forms', '0124_alter_candidateforms_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateforms',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circular_import_problem', to='training.tescandidate'),
        ),
    ]
