# Generated by Django 4.0.1 on 2022-02-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0065_formslist_class_name'),
        ('forms', '0125_alter_candidateforms_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndt15aexperienceverification',
            name='guideline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guideline_ndt', to='training.formslist'),
        ),
        migrations.AlterField(
            model_name='ndtcovid19',
            name='guideline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guideline_ndt_covid19', to='training.formslist'),
        ),
        migrations.AlterField(
            model_name='psl57b',
            name='guideline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guideline_psl_57b', to='training.formslist'),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='guideline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guideline_att_train', to='training.formslist'),
        ),
        migrations.AlterField(
            model_name='visiontest',
            name='guideline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guideline_vision_test', to='training.formslist'),
        ),
    ]
