# Generated by Django 4.0.1 on 2022-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0126_alter_ndt15aexperienceverification_guideline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateforms',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
