# Generated by Django 4.0.1 on 2022-03-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0068_courserequest_archived'),
        ('forms', '0128_rename_coursename_teslecfeedbackfrom_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesfrmexaminationattendance',
            name='event',
            field=models.ForeignKey(default=145, on_delete=django.db.models.deletion.CASCADE, related_name='event_att_training', to='training.event'),
            preserve_default=False,
        ),
    ]
