# Generated by Django 4.0.1 on 2022-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0129_tesfrmexaminationattendance_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslecfeedbackfrom',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
