# Generated by Django 4.0.1 on 2022-03-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0070_event_exam_att_file_event_traning_att_file'),
        ('forms', '0130_teslecfeedbackfrom_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesattcandidate',
            name='event',
            field=models.ForeignKey(default=146, on_delete=django.db.models.deletion.CASCADE, related_name='event_att_tes', to='training.event'),
            preserve_default=False,
        ),
    ]
