# Generated by Django 4.0.1 on 2022-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0131_tesattcandidate_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl30logexp',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
