# Generated by Django 4.0.1 on 2022-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0132_psl30logexp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl30initialform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
