# Generated by Django 4.0.4 on 2022-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0134_ndtcovid19_candidate_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateforms',
            name='submitted',
        ),
        migrations.AddField(
            model_name='candidateforms',
            name='candidate_confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateforms',
            name='confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
