# Generated by Django 4.0.6 on 2022-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0135_remove_candidateforms_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl57b',
            name='sponsorEmail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
