# Generated by Django 3.2.5 on 2021-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_readflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Candidate', 'Candidate')], max_length=10, null=True),
        ),
    ]
