# Generated by Django 3.2.5 on 2021-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Candidate', 'Candidate')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=4092, null=True),
        ),
    ]
