# Generated by Django 3.2.5 on 2021-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20211017_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='sentType',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Candidate', 'Candidate')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, choices=[('Form', 'Form'), ('Message', 'Message')], max_length=10, null=True),
        ),
    ]
