# Generated by Django 3.2.5 on 2021-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20211018_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='readFlag',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sentType',
        ),
        migrations.AddField(
            model_name='contact',
            name='messageType',
            field=models.CharField(blank=True, choices=[('Form', 'Form'), ('Message', 'Message')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Candidate', 'Candidate')], max_length=10, null=True),
        ),
    ]
