# Generated by Django 3.2.5 on 2021-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20211019_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='objID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
