# Generated by Django 3.2.5 on 2021-10-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_objid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='formName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
