# Generated by Django 4.0.1 on 2022-03-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messageType',
            field=models.CharField(blank=True, choices=[('Form', 'Form'), ('Message', 'Message'), ('Site', 'Site')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Candidate', 'Candidate'), ('Site', 'Site')], max_length=10, null=True),
        ),
    ]
