# Generated by Django 4.0.4 on 2022-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0002_remove_sidebar_code_remove_sidebar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenulevelone',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='submenulevelone',
            name='submenu',
            field=models.ManyToManyField(blank=True, null=True, to='settings.submenuleveltwo'),
        ),
    ]
