# Generated by Django 4.0.4 on 2022-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_submenuleveltwo_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenuleveltwo',
            name='href',
        ),
        migrations.AddField(
            model_name='sidebar',
            name='href',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
