# Generated by Django 4.0.4 on 2022-09-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0005_remove_submenuleveltwo_href_sidebar_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuLevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('code', models.CharField(blank=True, max_length=512, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.group')),
            ],
        ),
    ]
