# Generated by Django 4.0.4 on 2022-09-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_submenulevelthree'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuleveltwo',
            name='submenu',
            field=models.ManyToManyField(blank=True, null=True, to='settings.submenulevelthree'),
        ),
    ]
