# Generated by Django 4.0.4 on 2022-09-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0007_submenuleveltwo_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='href',
        ),
        migrations.RemoveField(
            model_name='submenuleveltwo',
            name='submenu',
        ),
        migrations.AlterField(
            model_name='submenulevelone',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='settings.submenuleveltwo'),
        ),
        migrations.AlterField(
            model_name='submenulevelone',
            name='submenu',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='SubMenuLevelThree',
        ),
    ]
