# Generated by Django 4.0.4 on 2022-09-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0008_remove_sidebar_href_remove_submenuleveltwo_submenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='href',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='submenulevelone',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='submenulevelone',
            name='submenu',
            field=models.ManyToManyField(blank=True, null=True, to='settings.submenuleveltwo'),
        ),
        migrations.CreateModel(
            name='SubMenuLevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('code', models.CharField(blank=True, max_length=512, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='submenuleveltwo',
            name='submenu',
            field=models.ManyToManyField(blank=True, null=True, to='settings.submenulevelthree'),
        ),
    ]
