# Generated by Django 3.2 on 2021-06-02 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('announcement_type', models.CharField(blank=True, choices=[('S', 'SMS'), ('E', 'Email')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_event', to='training.country')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('V', 'Virtual Accademy'), ('C', 'Class Rooom Based'), ('O', 'Online Zoom')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Country_location', to='training.country')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('passport_id', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_1', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_3', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_4', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_5', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_6', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_7', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_8', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('document_9', models.FileField(blank=True, null=True, upload_to='lecturer_document')),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(to='training.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='lecturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_event', to='training.lecturer'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_event', to='training.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_event', to='training.product'),
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('tes_candidate_id', models.CharField(blank=True, max_length=30, null=True)),
                ('sponsor_company', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_document')),
                ('document_1', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_3', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_4', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_5', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_6', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_7', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_8', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_9', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_10', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(to='training.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
