# Generated by Django 3.1.6 on 2021-04-20 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('document_1', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_3', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_4', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_5', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar')),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
