# Generated by Django 3.1.6 on 2021-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_candidateprofile_passport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='sponsor_company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
