# Generated by Django 3.2 on 2021-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_candidateprofile_sponsor_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
