# Generated by Django 3.2 on 2021-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_candidateprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('V', 'Virtual Access'), ('C', 'Class Rooom Based'), ('O', 'Online Zoom')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='document_6',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='document_7',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='document_8',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='document_9',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='twi_candidate_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
