# Generated by Django 3.2.4 on 2021-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='certificates',
            field=models.ManyToManyField(to='training.Certificate'),
        ),
    ]
