# Generated by Django 3.2 on 2021-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
