# Generated by Django 3.2.4 on 2021-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_lecturer_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='aboutMe',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
