# Generated by Django 3.2 on 2021-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
