# Generated by Django 3.2 on 2021-04-23 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 23, 10, 7, 18, 512403, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
