# Generated by Django 3.2.4 on 2021-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_lecturer_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='aboutMe',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='training.Certificate'),
        ),
    ]
