# Generated by Django 3.2 on 2021-04-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='candidates',
            field=models.ManyToManyField(to='training.CandidateProfile'),
        ),
    ]
