# Generated by Django 3.2 on 2021-04-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_remove_event_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='events',
            field=models.ManyToManyField(to='training.Event'),
        ),
    ]
