# Generated by Django 3.2.4 on 2021-06-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20210620_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='workHistory',
            field=models.ManyToManyField(blank=True, null=True, to='training.WorkHistory'),
        ),
    ]
