# Generated by Django 3.2.4 on 2021-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_candidateprofile_workhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='discription',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
