# Generated by Django 3.2.4 on 2021-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_workhistory_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='position',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='webSite',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='discription',
            field=models.CharField(blank=True, max_length=2024, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
