# Generated by Django 3.2 on 2021-04-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
