# Generated by Django 3.2 on 2021-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('V', 'Virtual Accademy'), ('C', 'Class Rooom Based'), ('O', 'Online Zoom')], max_length=1),
        ),
    ]
