# Generated by Django 3.2.4 on 2021-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_candidateprofile_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='country',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='sponsor_company',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='tes_candidate_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
