# Generated by Django 3.2.4 on 2021-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20210626_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postalCode',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
