# Generated by Django 3.2 on 2021-04-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lecturers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_event', to='training.lecturer'),
        ),
    ]
