# Generated by Django 3.2 on 2021-05-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_event_lecturers'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
