# Generated by Django 3.2 on 2021-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20210507_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
