# Generated by Django 3.2.4 on 2021-06-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('B', 'Class Room Course'), ('L', 'Online Live Zoom Course'), ('W', 'Online Live Zoom Course Weekend '), ('A', 'Online Virtual Academy Course'), ('X', 'Blended Course'), ('N', 'Non-Blended Course'), ('T', 'Online Training Only'), ('AP', 'Appreciation'), ('R', 'Refresh Course')], max_length=2),
        ),
    ]
