# Generated by Django 3.2 on 2021-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_lecturer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='passport_id',
            new_name='tes_candidate_id',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='note',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='twi_candidate_id',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='avatar',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_document'),
        ),
    ]
