# Generated by Django 3.2 on 2021-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20210516_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='document_10',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
    ]
