# Generated by Django 3.2 on 2021-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20210522_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
