# Generated by Django 3.2.4 on 2021-06-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20210628_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='country',
        ),
    ]
