# Generated by Django 3.2.4 on 2021-06-29 13:06

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_auto_20210629_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='mobile',
        ),
        migrations.AddField(
            model_name='event',
            name='candidates',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='training.CandidateProfile'),
        ),
    ]
