# Generated by Django 3.2.4 on 2021-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_auto_20210629_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='candidates',
            field=models.ManyToManyField(to='training.CandidateProfile'),
        ),
    ]
