# Generated by Django 3.2.4 on 2021-06-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_alter_event_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='events',
        ),
    ]
