# Generated by Django 3.2.4 on 2021-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_event_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='workHistory',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skills',
        ),
        migrations.AlterField(
            model_name='event',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, to='training.CandidateProfile'),
        ),
    ]
