# Generated by Django 3.2.4 on 2021-07-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0032_auto_20210722_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='formType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_cat_event', to='training.category'),
        ),
    ]
