# Generated by Django 3.2.4 on 2021-06-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0032_alter_event_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='aboutMe',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_1',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_10',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_2',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_3',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_4',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_5',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_6',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_7',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_8',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='document_9',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='sponsor_company',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='workHistory',
        ),
    ]
