# Generated by Django 3.2.4 on 2021-07-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0033_event_formtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='formType',
            new_name='formCategory',
        ),
    ]
