# Generated by Django 3.2.4 on 2021-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0033_auto_20210630_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='tes_candidate_id',
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
