# Generated by Django 3.2.4 on 2021-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_auto_20210630_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofileone',
            name='name',
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='aboutMe',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='training.Certificate'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='contact_number',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='customer_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_10',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_4',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_5',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_6',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_7',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_8',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='document_9',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='postal_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='training.CandidateProject'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='training.Skill'),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='sponsor_company',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='tes_candidate_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofileone',
            name='workHistory',
            field=models.ManyToManyField(blank=True, null=True, to='training.WorkHistory'),
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='training.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='customer_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
