# Generated by Django 3.2.5 on 2021-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0035_tescandidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='training.Event'),
        ),
    ]
