# Generated by Django 3.2.4 on 2021-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0036_auto_20210630_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='customer_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='tes_candidate_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
