# Generated by Django 3.2.4 on 2021-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_auto_20210630_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='aboutMe',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='contact_number',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='postal_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='sponsor_company',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
