# Generated by Django 3.2.5 on 2021-08-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_candidateprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tescandidate',
            old_name='sponsor_company',
            new_name='emergencyContact',
        ),
    ]
