# Generated by Django 3.2.4 on 2021-06-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_auto_20210630_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_10',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_4',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_5',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_6',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_7',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_8',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='document_9',
            field=models.FileField(blank=True, null=True, upload_to='candidate_document'),
        ),
        migrations.AddField(
            model_name='skill',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_document'),
        ),
    ]
