# Generated by Django 3.2.5 on 2021-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_rename_sponsor_company_tescandidate_emergencycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='formCategory',
        ),
        migrations.AddField(
            model_name='event',
            name='formCategory',
            field=models.ManyToManyField(to='training.Category'),
        ),
    ]
