# Generated by Django 3.2.4 on 2021-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_auto_20210630_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='training.Certificate'),
        ),
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='training.CandidateProject'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='training.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='workHistory',
            field=models.ManyToManyField(blank=True, null=True, to='training.WorkHistory'),
        ),
    ]
