# Generated by Django 3.2.5 on 2021-08-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_auto_20210824_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formCategory',
            field=models.ManyToManyField(blank=True, null=True, to='training.Category'),
        ),
    ]
