# Generated by Django 3.2.5 on 2021-10-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_alter_event_formcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='currentCompany',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='tescandidate',
            name='website',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
