# Generated by Django 3.2.4 on 2021-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_auto_20210630_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('tes_candidate_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('sponsor_company', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=1024, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('aboutMe', models.CharField(blank=True, max_length=5000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_document')),
                ('document_1', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_3', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_4', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_5', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_6', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_7', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_8', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_9', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_10', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificates', models.ManyToManyField(blank=True, null=True, to='training.Certificate')),
                ('project', models.ManyToManyField(blank=True, null=True, to='training.CandidateProject')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='training.Skill')),
                ('workHistory', models.ManyToManyField(blank=True, null=True, to='training.WorkHistory')),
            ],
        ),
    ]
