# Generated by Django 3.2.4 on 2021-06-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0042_auto_20210630_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='candidate',
            field=models.ManyToManyField(blank=True, null=True, to='training.TesCandidate'),
        ),
    ]
