# Generated by Django 3.2.4 on 2021-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0043_event_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='middleName',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
