# Generated by Django 3.2.4 on 2021-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0044_tescandidate_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='sponsorType',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
