# Generated by Django 3.2.4 on 2021-07-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0045_tescandidate_sponsortype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tescandidate',
            name='sponsorType',
        ),
    ]
