# Generated by Django 3.2.5 on 2022-01-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0046_auto_20220112_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
