# Generated by Django 4.0.1 on 2022-01-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0052_courserequest_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
    ]
