# Generated by Django 3.2.5 on 2022-01-24 08:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0052_courserequest_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default='teset'),
            preserve_default=False,
        ),
    ]
