# Generated by Django 3.2.5 on 2022-01-24 09:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0053_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=tinymce.models.HTMLField(default='Test'),
            preserve_default=False,
        ),
    ]
