# Generated by Django 4.0.1 on 2022-01-27 08:25

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0054_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=tinymce_4.fields.TinyMCEModelField(default='test'),
            preserve_default=False,
        ),
    ]
