# Generated by Django 4.0.1 on 2022-01-31 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0055_productcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('middleName', models.CharField(blank=True, max_length=1024, null=True)),
                ('tes_candidate_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=1024, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('aboutMe', models.CharField(blank=True, max_length=5000, null=True)),
                ('currentCompany', models.CharField(blank=True, max_length=5000, null=True)),
                ('website', models.CharField(blank=True, max_length=5000, null=True)),
                ('facebook', models.CharField(blank=True, max_length=5000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=5000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=5000, null=True)),
                ('skype', models.CharField(blank=True, max_length=5000, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=5000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_document')),
                ('document_1', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_3', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_4', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_5', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_6', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_7', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_8', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_9', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('document_10', models.FileField(blank=True, null=True, upload_to='candidate_document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificates', models.ManyToManyField(blank=True, null=True, to='training.Certificate')),
                ('forms', models.ManyToManyField(blank=True, null=True, to='training.FormsList')),
                ('project', models.ManyToManyField(blank=True, null=True, to='training.CandidateProject')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='training.Skill')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workHistory', models.ManyToManyField(blank=True, null=True, to='training.WorkHistory')),
            ],
        ),
    ]
