# Generated by Django 4.0.1 on 2022-01-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0056_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='currentCompany',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='tes_candidate_id',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='website',
        ),
    ]
