# Generated by Django 4.0.1 on 2022-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0058_alter_courserequest_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
