# Generated by Django 4.0.1 on 2022-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0059_product_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
