# Generated by Django 4.0.1 on 2022-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0061_tescandidate_form_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
