# Generated by Django 4.0.1 on 2022-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0125_alter_candidateforms_candidate'),
        ('training', '0062_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='candidate_forms',
            field=models.ManyToManyField(blank=True, null=True, related_name='can_forms', to='forms.CandidateForms'),
        ),
    ]
