# Generated by Django 4.0.1 on 2022-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0063_tescandidate_candidate_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='formslist',
            name='internal_link_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
