# Generated by Django 4.0.1 on 2022-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0064_formslist_internal_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formslist',
            name='class_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
