# Generated by Django 4.0.1 on 2022-03-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0065_formslist_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='location',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
