# Generated by Django 4.0.1 on 2022-03-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0066_tescandidate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='readFlag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
