# Generated by Django 4.0.1 on 2022-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0067_courserequest_readflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
