# Generated by Django 4.0.1 on 2022-03-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0068_courserequest_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='disable_timesheet',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
