# Generated by Django 4.0.1 on 2022-03-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0070_event_exam_att_file_event_traning_att_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
