# Generated by Django 4.0.4 on 2022-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0076_alter_tescandidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='currentPosition',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tescandidate',
            name='currentCompany',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tescandidate',
            name='facebook',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tescandidate',
            name='instagram',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tescandidate',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tescandidate',
            name='skype',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tescandidate',
            name='twitter',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tescandidate',
            name='website',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
