# Generated by Django 4.0.4 on 2022-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0077_tescandidate_currentposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deliveryMethod',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
