# Generated by Django 4.0.6 on 2022-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0081_tescandidate_altoneemail_tescandidate_alttwoemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tescandidate',
            name='notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
