from distutils.core import setup

setup(
    name='QuickCRM',
    version='0.1',
    packages=['lib', 'lib.python3.8', 'lib.python3.8.site-packages', 'lib.python3.8.site-packages.PIL',
              'lib.python3.8.site-packages.lml', 'lib.python3.8.site-packages.odf', 'lib.python3.8.site-packages.pip',
              'lib.python3.8.site-packages.pip._vendor', 'lib.python3.8.site-packages.pip._internal',
              'lib.python3.8.site-packages.pip._internal.cli', 'lib.python3.8.site-packages.pip._internal.req',
              'lib.python3.8.site-packages.pip._internal.vcs', 'lib.python3.8.site-packages.pip._internal.index',
              'lib.python3.8.site-packages.pip._internal.utils', 'lib.python3.8.site-packages.pip._internal.models',
              'lib.python3.8.site-packages.pip._internal.network', 'lib.python3.8.site-packages.pip._internal.commands',
              'lib.python3.8.site-packages.pip._internal.operations',
              'lib.python3.8.site-packages.pip._internal.operations.build',
              'lib.python3.8.site-packages.pip._internal.operations.install',
              'lib.python3.8.site-packages.pip._internal.distributions', 'lib.python3.8.site-packages.amqp',
              'lib.python3.8.site-packages.idna', 'lib.python3.8.site-packages.mypy',
              'lib.python3.8.site-packages.mypy.test', 'lib.python3.8.site-packages.mypy.dmypy',
              'lib.python3.8.site-packages.mypy.server', 'lib.python3.8.site-packages.mypy.plugins',
              'lib.python3.8.site-packages.pytz', 'lib.python3.8.site-packages.vine',
              'lib.python3.8.site-packages.xlrd', 'lib.python3.8.site-packages.xlwt',
              'lib.python3.8.site-packages.yaml', 'lib.python3.8.site-packages._yaml',
              'lib.python3.8.site-packages.click', 'lib.python3.8.site-packages.kombu',
              'lib.python3.8.site-packages.kombu.utils', 'lib.python3.8.site-packages.kombu.transport',
              'lib.python3.8.site-packages.kombu.transport.virtual',
              'lib.python3.8.site-packages.kombu.transport.sqlalchemy',
              'lib.python3.8.site-packages.kombu.asynchronous', 'lib.python3.8.site-packages.kombu.asynchronous.aws',
              'lib.python3.8.site-packages.kombu.asynchronous.aws.sqs',
              'lib.python3.8.site-packages.kombu.asynchronous.http', 'lib.python3.8.site-packages.mypyc',
              'lib.python3.8.site-packages.mypyc.ir', 'lib.python3.8.site-packages.mypyc.test',
              'lib.python3.8.site-packages.mypyc.codegen', 'lib.python3.8.site-packages.mypyc.irbuild',
              'lib.python3.8.site-packages.mypyc.analysis', 'lib.python3.8.site-packages.mypyc.transform',
              'lib.python3.8.site-packages.mypyc.primitives', 'lib.python3.8.site-packages.numpy',
              'lib.python3.8.site-packages.numpy.ma', 'lib.python3.8.site-packages.numpy.ma.tests',
              'lib.python3.8.site-packages.numpy.doc', 'lib.python3.8.site-packages.numpy.fft',
              'lib.python3.8.site-packages.numpy.fft.tests', 'lib.python3.8.site-packages.numpy.lib',
              'lib.python3.8.site-packages.numpy.lib.tests', 'lib.python3.8.site-packages.numpy.core',
              'lib.python3.8.site-packages.numpy.core.tests', 'lib.python3.8.site-packages.numpy.f2py',
              'lib.python3.8.site-packages.numpy.f2py.tests', 'lib.python3.8.site-packages.numpy.tests',
              'lib.python3.8.site-packages.numpy.compat', 'lib.python3.8.site-packages.numpy.compat.tests',
              'lib.python3.8.site-packages.numpy.linalg', 'lib.python3.8.site-packages.numpy.linalg.tests',
              'lib.python3.8.site-packages.numpy.random', 'lib.python3.8.site-packages.numpy.random.tests',
              'lib.python3.8.site-packages.numpy.random.tests.data', 'lib.python3.8.site-packages.numpy.typing',
              'lib.python3.8.site-packages.numpy.typing.tests', 'lib.python3.8.site-packages.numpy.testing',
              'lib.python3.8.site-packages.numpy.testing.tests', 'lib.python3.8.site-packages.numpy.testing._private',
              'lib.python3.8.site-packages.numpy.distutils', 'lib.python3.8.site-packages.numpy.distutils.tests',
              'lib.python3.8.site-packages.numpy.distutils.command',
              'lib.python3.8.site-packages.numpy.distutils.fcompiler', 'lib.python3.8.site-packages.numpy.matrixlib',
              'lib.python3.8.site-packages.numpy.matrixlib.tests', 'lib.python3.8.site-packages.numpy.polynomial',
              'lib.python3.8.site-packages.numpy.polynomial.tests', 'lib.python3.8.site-packages.polls',
              'lib.python3.8.site-packages.redis', 'lib.python3.8.site-packages.wheel',
              'lib.python3.8.site-packages.wheel.cli', 'lib.python3.8.site-packages.braces',
              'lib.python3.8.site-packages.braces.views', 'lib.python3.8.site-packages.celery',
              'lib.python3.8.site-packages.celery.app', 'lib.python3.8.site-packages.celery.bin',
              'lib.python3.8.site-packages.celery.apps', 'lib.python3.8.site-packages.celery.utils',
              'lib.python3.8.site-packages.celery.utils.static', 'lib.python3.8.site-packages.celery.utils.dispatch',
              'lib.python3.8.site-packages.celery.events', 'lib.python3.8.site-packages.celery.fixups',
              'lib.python3.8.site-packages.celery.worker', 'lib.python3.8.site-packages.celery.worker.consumer',
              'lib.python3.8.site-packages.celery.contrib', 'lib.python3.8.site-packages.celery.contrib.testing',
              'lib.python3.8.site-packages.celery.loaders', 'lib.python3.8.site-packages.celery.backends',
              'lib.python3.8.site-packages.celery.backends.database', 'lib.python3.8.site-packages.celery.security',
              'lib.python3.8.site-packages.celery.concurrency', 'lib.python3.8.site-packages.django',
              'lib.python3.8.site-packages.django.db', 'lib.python3.8.site-packages.django.db.models',
              'lib.python3.8.site-packages.django.db.models.sql', 'lib.python3.8.site-packages.django.db.models.fields',
              'lib.python3.8.site-packages.django.db.models.functions',
              'lib.python3.8.site-packages.django.db.backends', 'lib.python3.8.site-packages.django.db.backends.base',
              'lib.python3.8.site-packages.django.db.backends.dummy',
              'lib.python3.8.site-packages.django.db.backends.mysql',
              'lib.python3.8.site-packages.django.db.backends.oracle',
              'lib.python3.8.site-packages.django.db.backends.sqlite3',
              'lib.python3.8.site-packages.django.db.backends.postgresql',
              'lib.python3.8.site-packages.django.db.migrations',
              'lib.python3.8.site-packages.django.db.migrations.operations', 'lib.python3.8.site-packages.django.apps',
              'lib.python3.8.site-packages.django.conf', 'lib.python3.8.site-packages.django.conf.urls',
              'lib.python3.8.site-packages.django.conf.locale', 'lib.python3.8.site-packages.django.conf.locale.ar',
              'lib.python3.8.site-packages.django.conf.locale.az', 'lib.python3.8.site-packages.django.conf.locale.bg',
              'lib.python3.8.site-packages.django.conf.locale.bn', 'lib.python3.8.site-packages.django.conf.locale.bs',
              'lib.python3.8.site-packages.django.conf.locale.ca', 'lib.python3.8.site-packages.django.conf.locale.cs',
              'lib.python3.8.site-packages.django.conf.locale.cy', 'lib.python3.8.site-packages.django.conf.locale.da',
              'lib.python3.8.site-packages.django.conf.locale.de', 'lib.python3.8.site-packages.django.conf.locale.el',
              'lib.python3.8.site-packages.django.conf.locale.en', 'lib.python3.8.site-packages.django.conf.locale.eo',
              'lib.python3.8.site-packages.django.conf.locale.es', 'lib.python3.8.site-packages.django.conf.locale.et',
              'lib.python3.8.site-packages.django.conf.locale.eu', 'lib.python3.8.site-packages.django.conf.locale.fa',
              'lib.python3.8.site-packages.django.conf.locale.fi', 'lib.python3.8.site-packages.django.conf.locale.fr',
              'lib.python3.8.site-packages.django.conf.locale.fy', 'lib.python3.8.site-packages.django.conf.locale.ga',
              'lib.python3.8.site-packages.django.conf.locale.gd', 'lib.python3.8.site-packages.django.conf.locale.gl',
              'lib.python3.8.site-packages.django.conf.locale.he', 'lib.python3.8.site-packages.django.conf.locale.hi',
              'lib.python3.8.site-packages.django.conf.locale.hr', 'lib.python3.8.site-packages.django.conf.locale.hu',
              'lib.python3.8.site-packages.django.conf.locale.id', 'lib.python3.8.site-packages.django.conf.locale.ig',
              'lib.python3.8.site-packages.django.conf.locale.is', 'lib.python3.8.site-packages.django.conf.locale.it',
              'lib.python3.8.site-packages.django.conf.locale.ja', 'lib.python3.8.site-packages.django.conf.locale.ka',
              'lib.python3.8.site-packages.django.conf.locale.km', 'lib.python3.8.site-packages.django.conf.locale.kn',
              'lib.python3.8.site-packages.django.conf.locale.ko', 'lib.python3.8.site-packages.django.conf.locale.ky',
              'lib.python3.8.site-packages.django.conf.locale.lt', 'lib.python3.8.site-packages.django.conf.locale.lv',
              'lib.python3.8.site-packages.django.conf.locale.mk', 'lib.python3.8.site-packages.django.conf.locale.ml',
              'lib.python3.8.site-packages.django.conf.locale.mn', 'lib.python3.8.site-packages.django.conf.locale.nb',
              'lib.python3.8.site-packages.django.conf.locale.nl', 'lib.python3.8.site-packages.django.conf.locale.nn',
              'lib.python3.8.site-packages.django.conf.locale.pl', 'lib.python3.8.site-packages.django.conf.locale.pt',
              'lib.python3.8.site-packages.django.conf.locale.ro', 'lib.python3.8.site-packages.django.conf.locale.ru',
              'lib.python3.8.site-packages.django.conf.locale.sk', 'lib.python3.8.site-packages.django.conf.locale.sl',
              'lib.python3.8.site-packages.django.conf.locale.sq', 'lib.python3.8.site-packages.django.conf.locale.sr',
              'lib.python3.8.site-packages.django.conf.locale.sv', 'lib.python3.8.site-packages.django.conf.locale.ta',
              'lib.python3.8.site-packages.django.conf.locale.te', 'lib.python3.8.site-packages.django.conf.locale.tg',
              'lib.python3.8.site-packages.django.conf.locale.th', 'lib.python3.8.site-packages.django.conf.locale.tk',
              'lib.python3.8.site-packages.django.conf.locale.tr', 'lib.python3.8.site-packages.django.conf.locale.uk',
              'lib.python3.8.site-packages.django.conf.locale.uz', 'lib.python3.8.site-packages.django.conf.locale.vi',
              'lib.python3.8.site-packages.django.conf.locale.ar_DZ',
              'lib.python3.8.site-packages.django.conf.locale.de_CH',
              'lib.python3.8.site-packages.django.conf.locale.en_AU',
              'lib.python3.8.site-packages.django.conf.locale.en_GB',
              'lib.python3.8.site-packages.django.conf.locale.es_AR',
              'lib.python3.8.site-packages.django.conf.locale.es_CO',
              'lib.python3.8.site-packages.django.conf.locale.es_MX',
              'lib.python3.8.site-packages.django.conf.locale.es_NI',
              'lib.python3.8.site-packages.django.conf.locale.es_PR',
              'lib.python3.8.site-packages.django.conf.locale.pt_BR',
              'lib.python3.8.site-packages.django.conf.locale.sr_Latn',
              'lib.python3.8.site-packages.django.conf.locale.zh_Hans',
              'lib.python3.8.site-packages.django.conf.locale.zh_Hant', 'lib.python3.8.site-packages.django.core',
              'lib.python3.8.site-packages.django.core.mail', 'lib.python3.8.site-packages.django.core.mail.backends',
              'lib.python3.8.site-packages.django.core.cache', 'lib.python3.8.site-packages.django.core.cache.backends',
              'lib.python3.8.site-packages.django.core.files', 'lib.python3.8.site-packages.django.core.checks',
              'lib.python3.8.site-packages.django.core.checks.security',
              'lib.python3.8.site-packages.django.core.checks.compatibility',
              'lib.python3.8.site-packages.django.core.servers', 'lib.python3.8.site-packages.django.core.handlers',
              'lib.python3.8.site-packages.django.core.management',
              'lib.python3.8.site-packages.django.core.management.commands',
              'lib.python3.8.site-packages.django.core.serializers', 'lib.python3.8.site-packages.django.http',
              'lib.python3.8.site-packages.django.test', 'lib.python3.8.site-packages.django.urls',
              'lib.python3.8.site-packages.django.forms', 'lib.python3.8.site-packages.django.utils',
              'lib.python3.8.site-packages.django.utils.translation', 'lib.python3.8.site-packages.django.views',
              'lib.python3.8.site-packages.django.views.generic', 'lib.python3.8.site-packages.django.views.decorators',
              'lib.python3.8.site-packages.django.contrib', 'lib.python3.8.site-packages.django.contrib.gis',
              'lib.python3.8.site-packages.django.contrib.gis.db',
              'lib.python3.8.site-packages.django.contrib.gis.db.models',
              'lib.python3.8.site-packages.django.contrib.gis.db.models.sql',
              'lib.python3.8.site-packages.django.contrib.gis.db.backends',
              'lib.python3.8.site-packages.django.contrib.gis.db.backends.base',
              'lib.python3.8.site-packages.django.contrib.gis.db.backends.mysql',
              'lib.python3.8.site-packages.django.contrib.gis.db.backends.oracle',
              'lib.python3.8.site-packages.django.contrib.gis.db.backends.postgis',
              'lib.python3.8.site-packages.django.contrib.gis.db.backends.spatialite',
              'lib.python3.8.site-packages.django.contrib.gis.gdal',
              'lib.python3.8.site-packages.django.contrib.gis.gdal.raster',
              'lib.python3.8.site-packages.django.contrib.gis.gdal.prototypes',
              'lib.python3.8.site-packages.django.contrib.gis.geos',
              'lib.python3.8.site-packages.django.contrib.gis.geos.prototypes',
              'lib.python3.8.site-packages.django.contrib.gis.admin',
              'lib.python3.8.site-packages.django.contrib.gis.forms',
              'lib.python3.8.site-packages.django.contrib.gis.utils',
              'lib.python3.8.site-packages.django.contrib.gis.geoip2',
              'lib.python3.8.site-packages.django.contrib.gis.sitemaps',
              'lib.python3.8.site-packages.django.contrib.gis.management',
              'lib.python3.8.site-packages.django.contrib.gis.management.commands',
              'lib.python3.8.site-packages.django.contrib.gis.serializers',
              'lib.python3.8.site-packages.django.contrib.auth',
              'lib.python3.8.site-packages.django.contrib.auth.handlers',
              'lib.python3.8.site-packages.django.contrib.auth.management',
              'lib.python3.8.site-packages.django.contrib.auth.management.commands',
              'lib.python3.8.site-packages.django.contrib.auth.migrations',
              'lib.python3.8.site-packages.django.contrib.admin',
              'lib.python3.8.site-packages.django.contrib.admin.views',
              'lib.python3.8.site-packages.django.contrib.admin.migrations',
              'lib.python3.8.site-packages.django.contrib.admin.templatetags',
              'lib.python3.8.site-packages.django.contrib.sites',
              'lib.python3.8.site-packages.django.contrib.sites.migrations',
              'lib.python3.8.site-packages.django.contrib.humanize',
              'lib.python3.8.site-packages.django.contrib.humanize.templatetags',
              'lib.python3.8.site-packages.django.contrib.messages',
              'lib.python3.8.site-packages.django.contrib.messages.storage',
              'lib.python3.8.site-packages.django.contrib.postgres',
              'lib.python3.8.site-packages.django.contrib.postgres.forms',
              'lib.python3.8.site-packages.django.contrib.postgres.fields',
              'lib.python3.8.site-packages.django.contrib.postgres.aggregates',
              'lib.python3.8.site-packages.django.contrib.sessions',
              'lib.python3.8.site-packages.django.contrib.sessions.backends',
              'lib.python3.8.site-packages.django.contrib.sessions.management',
              'lib.python3.8.site-packages.django.contrib.sessions.management.commands',
              'lib.python3.8.site-packages.django.contrib.sessions.migrations',
              'lib.python3.8.site-packages.django.contrib.sitemaps',
              'lib.python3.8.site-packages.django.contrib.sitemaps.management',
              'lib.python3.8.site-packages.django.contrib.sitemaps.management.commands',
              'lib.python3.8.site-packages.django.contrib.admindocs',
              'lib.python3.8.site-packages.django.contrib.flatpages',
              'lib.python3.8.site-packages.django.contrib.flatpages.migrations',
              'lib.python3.8.site-packages.django.contrib.flatpages.templatetags',
              'lib.python3.8.site-packages.django.contrib.redirects',
              'lib.python3.8.site-packages.django.contrib.redirects.migrations',
              'lib.python3.8.site-packages.django.contrib.staticfiles',
              'lib.python3.8.site-packages.django.contrib.staticfiles.management',
              'lib.python3.8.site-packages.django.contrib.staticfiles.management.commands',
              'lib.python3.8.site-packages.django.contrib.syndication',
              'lib.python3.8.site-packages.django.contrib.contenttypes',
              'lib.python3.8.site-packages.django.contrib.contenttypes.management',
              'lib.python3.8.site-packages.django.contrib.contenttypes.management.commands',
              'lib.python3.8.site-packages.django.contrib.contenttypes.migrations',
              'lib.python3.8.site-packages.django.dispatch', 'lib.python3.8.site-packages.django.template',
              'lib.python3.8.site-packages.django.template.loaders',
              'lib.python3.8.site-packages.django.template.backends', 'lib.python3.8.site-packages.django.middleware',
              'lib.python3.8.site-packages.django.templatetags', 'lib.python3.8.site-packages.mysite',
              'lib.python3.8.site-packages.pandas', 'lib.python3.8.site-packages.pandas.io',
              'lib.python3.8.site-packages.pandas.io.sas', 'lib.python3.8.site-packages.pandas.io.json',
              'lib.python3.8.site-packages.pandas.io.excel', 'lib.python3.8.site-packages.pandas.io.formats',
              'lib.python3.8.site-packages.pandas.io.clipboard', 'lib.python3.8.site-packages.pandas.api',
              'lib.python3.8.site-packages.pandas.api.types', 'lib.python3.8.site-packages.pandas.api.indexers',
              'lib.python3.8.site-packages.pandas.api.extensions', 'lib.python3.8.site-packages.pandas.core',
              'lib.python3.8.site-packages.pandas.core.ops', 'lib.python3.8.site-packages.pandas.core.util',
              'lib.python3.8.site-packages.pandas.core.tools', 'lib.python3.8.site-packages.pandas.core.arrays',
              'lib.python3.8.site-packages.pandas.core.arrays.sparse', 'lib.python3.8.site-packages.pandas.core.dtypes',
              'lib.python3.8.site-packages.pandas.core.sparse', 'lib.python3.8.site-packages.pandas.core.window',
              'lib.python3.8.site-packages.pandas.core.groupby', 'lib.python3.8.site-packages.pandas.core.indexes',
              'lib.python3.8.site-packages.pandas.core.reshape', 'lib.python3.8.site-packages.pandas.core.strings',
              'lib.python3.8.site-packages.pandas.core.internals',
              'lib.python3.8.site-packages.pandas.core.array_algos',
              'lib.python3.8.site-packages.pandas.core.computation', 'lib.python3.8.site-packages.pandas.util',
              'lib.python3.8.site-packages.pandas._libs', 'lib.python3.8.site-packages.pandas._libs.tslibs',
              'lib.python3.8.site-packages.pandas._libs.window', 'lib.python3.8.site-packages.pandas.tests',
              'lib.python3.8.site-packages.pandas.tests.io', 'lib.python3.8.site-packages.pandas.tests.io.sas',
              'lib.python3.8.site-packages.pandas.tests.io.json', 'lib.python3.8.site-packages.pandas.tests.io.excel',
              'lib.python3.8.site-packages.pandas.tests.io.parser',
              'lib.python3.8.site-packages.pandas.tests.io.formats',
              'lib.python3.8.site-packages.pandas.tests.io.pytables', 'lib.python3.8.site-packages.pandas.tests.api',
              'lib.python3.8.site-packages.pandas.tests.base', 'lib.python3.8.site-packages.pandas.tests.libs',
              'lib.python3.8.site-packages.pandas.tests.util', 'lib.python3.8.site-packages.pandas.tests.frame',
              'lib.python3.8.site-packages.pandas.tests.frame.apply',
              'lib.python3.8.site-packages.pandas.tests.frame.methods',
              'lib.python3.8.site-packages.pandas.tests.frame.indexing',
              'lib.python3.8.site-packages.pandas.tests.tools', 'lib.python3.8.site-packages.pandas.tests.arrays',
              'lib.python3.8.site-packages.pandas.tests.arrays.masked',
              'lib.python3.8.site-packages.pandas.tests.arrays.sparse',
              'lib.python3.8.site-packages.pandas.tests.arrays.boolean',
              'lib.python3.8.site-packages.pandas.tests.arrays.integer',
              'lib.python3.8.site-packages.pandas.tests.arrays.string_',
              'lib.python3.8.site-packages.pandas.tests.arrays.floating',
              'lib.python3.8.site-packages.pandas.tests.arrays.interval',
              'lib.python3.8.site-packages.pandas.tests.arrays.categorical',
              'lib.python3.8.site-packages.pandas.tests.config', 'lib.python3.8.site-packages.pandas.tests.dtypes',
              'lib.python3.8.site-packages.pandas.tests.dtypes.cast', 'lib.python3.8.site-packages.pandas.tests.scalar',
              'lib.python3.8.site-packages.pandas.tests.scalar.period',
              'lib.python3.8.site-packages.pandas.tests.scalar.interval',
              'lib.python3.8.site-packages.pandas.tests.scalar.timedelta',
              'lib.python3.8.site-packages.pandas.tests.scalar.timestamp',
              'lib.python3.8.site-packages.pandas.tests.series',
              'lib.python3.8.site-packages.pandas.tests.series.apply',
              'lib.python3.8.site-packages.pandas.tests.series.methods',
              'lib.python3.8.site-packages.pandas.tests.series.indexing',
              'lib.python3.8.site-packages.pandas.tests.series.accessors',
              'lib.python3.8.site-packages.pandas.tests.tslibs', 'lib.python3.8.site-packages.pandas.tests.window',
              'lib.python3.8.site-packages.pandas.tests.window.moments',
              'lib.python3.8.site-packages.pandas.tests.generic',
              'lib.python3.8.site-packages.pandas.tests.generic.methods',
              'lib.python3.8.site-packages.pandas.tests.groupby',
              'lib.python3.8.site-packages.pandas.tests.groupby.aggregate',
              'lib.python3.8.site-packages.pandas.tests.groupby.transform',
              'lib.python3.8.site-packages.pandas.tests.indexes',
              'lib.python3.8.site-packages.pandas.tests.indexes.multi',
              'lib.python3.8.site-packages.pandas.tests.indexes.period',
              'lib.python3.8.site-packages.pandas.tests.indexes.ranges',
              'lib.python3.8.site-packages.pandas.tests.indexes.numeric',
              'lib.python3.8.site-packages.pandas.tests.indexes.interval',
              'lib.python3.8.site-packages.pandas.tests.indexes.datetimes',
              'lib.python3.8.site-packages.pandas.tests.indexes.base_class',
              'lib.python3.8.site-packages.pandas.tests.indexes.timedeltas',
              'lib.python3.8.site-packages.pandas.tests.indexes.categorical',
              'lib.python3.8.site-packages.pandas.tests.reshape',
              'lib.python3.8.site-packages.pandas.tests.reshape.merge',
              'lib.python3.8.site-packages.pandas.tests.reshape.concat',
              'lib.python3.8.site-packages.pandas.tests.tseries',
              'lib.python3.8.site-packages.pandas.tests.tseries.holiday',
              'lib.python3.8.site-packages.pandas.tests.tseries.offsets',
              'lib.python3.8.site-packages.pandas.tests.tseries.frequencies',
              'lib.python3.8.site-packages.pandas.tests.indexing',
              'lib.python3.8.site-packages.pandas.tests.indexing.interval',
              'lib.python3.8.site-packages.pandas.tests.indexing.multiindex',
              'lib.python3.8.site-packages.pandas.tests.plotting',
              'lib.python3.8.site-packages.pandas.tests.plotting.frame',
              'lib.python3.8.site-packages.pandas.tests.resample', 'lib.python3.8.site-packages.pandas.tests.extension',
              'lib.python3.8.site-packages.pandas.tests.extension.base',
              'lib.python3.8.site-packages.pandas.tests.extension.json',
              'lib.python3.8.site-packages.pandas.tests.extension.list',
              'lib.python3.8.site-packages.pandas.tests.extension.arrow',
              'lib.python3.8.site-packages.pandas.tests.extension.decimal',
              'lib.python3.8.site-packages.pandas.tests.internals',
              'lib.python3.8.site-packages.pandas.tests.arithmetic',
              'lib.python3.8.site-packages.pandas.tests.reductions',
              'lib.python3.8.site-packages.pandas.tests.computation', 'lib.python3.8.site-packages.pandas.arrays',
              'lib.python3.8.site-packages.pandas.compat', 'lib.python3.8.site-packages.pandas.compat.numpy',
              'lib.python3.8.site-packages.pandas.errors', 'lib.python3.8.site-packages.pandas._config',
              'lib.python3.8.site-packages.pandas.tseries', 'lib.python3.8.site-packages.pandas.plotting',
              'lib.python3.8.site-packages.pandas.plotting._matplotlib', 'lib.python3.8.site-packages.pep517',
              'lib.python3.8.site-packages.pytoml', 'lib.python3.8.site-packages.tablib',
              'lib.python3.8.site-packages.tablib.formats', 'lib.python3.8.site-packages.tablib.packages',
              'lib.python3.8.site-packages.tablib.packages.dbfpy', 'lib.python3.8.site-packages.asgiref',
              'lib.python3.8.site-packages.certifi', 'lib.python3.8.site-packages.chardet',
              'lib.python3.8.site-packages.chardet.cli', 'lib.python3.8.site-packages.distlib',
              'lib.python3.8.site-packages.distlib._backport', 'lib.python3.8.site-packages.msgpack',
              'lib.python3.8.site-packages.pyexcel', 'lib.python3.8.site-packages.pyexcel.ext',
              'lib.python3.8.site-packages.pyexcel.plugins', 'lib.python3.8.site-packages.pyexcel.plugins.parsers',
              'lib.python3.8.site-packages.pyexcel.plugins.sources',
              'lib.python3.8.site-packages.pyexcel.plugins.sources.pydata',
              'lib.python3.8.site-packages.pyexcel.plugins.renderers', 'lib.python3.8.site-packages.pyexcel.internal',
              'lib.python3.8.site-packages.pyexcel.internal.sheets', 'lib.python3.8.site-packages.pyexcel.docstrings',
              'lib.python3.8.site-packages.urllib3', 'lib.python3.8.site-packages.urllib3.util',
              'lib.python3.8.site-packages.urllib3.contrib',
              'lib.python3.8.site-packages.urllib3.contrib._securetransport',
              'lib.python3.8.site-packages.urllib3.packages', 'lib.python3.8.site-packages.urllib3.packages.backports',
              'lib.python3.8.site-packages.urllib3.packages.ssl_match_hostname', 'lib.python3.8.site-packages.wcwidth',
              'lib.python3.8.site-packages.wcwidth.tests', 'lib.python3.8.site-packages.MarkupPy',
              'lib.python3.8.site-packages.billiard', 'lib.python3.8.site-packages.billiard.dummy',
              'lib.python3.8.site-packages.colorama', 'lib.python3.8.site-packages.dateutil',
              'lib.python3.8.site-packages.dateutil.tz', 'lib.python3.8.site-packages.dateutil.parser',
              'lib.python3.8.site-packages.dateutil.zoneinfo', 'lib.python3.8.site-packages.gunicorn',
              'lib.python3.8.site-packages.gunicorn.app', 'lib.python3.8.site-packages.gunicorn.http',
              'lib.python3.8.site-packages.gunicorn.workers', 'lib.python3.8.site-packages.gunicorn.instrument',
              'lib.python3.8.site-packages.html5lib', 'lib.python3.8.site-packages.html5lib._trie',
              'lib.python3.8.site-packages.html5lib.filters', 'lib.python3.8.site-packages.html5lib.treewalkers',
              'lib.python3.8.site-packages.html5lib.treeadapters', 'lib.python3.8.site-packages.html5lib.treebuilders',
              'lib.python3.8.site-packages.lockfile', 'lib.python3.8.site-packages.markdown',
              'lib.python3.8.site-packages.markdown.extensions', 'lib.python3.8.site-packages.openpyxl',
              'lib.python3.8.site-packages.openpyxl.xml', 'lib.python3.8.site-packages.openpyxl.cell',
              'lib.python3.8.site-packages.openpyxl.chart', 'lib.python3.8.site-packages.openpyxl.pivot',
              'lib.python3.8.site-packages.openpyxl.utils', 'lib.python3.8.site-packages.openpyxl.compat',
              'lib.python3.8.site-packages.openpyxl.reader', 'lib.python3.8.site-packages.openpyxl.styles',
              'lib.python3.8.site-packages.openpyxl.writer', 'lib.python3.8.site-packages.openpyxl.drawing',
              'lib.python3.8.site-packages.openpyxl.formula', 'lib.python3.8.site-packages.openpyxl.comments',
              'lib.python3.8.site-packages.openpyxl.workbook',
              'lib.python3.8.site-packages.openpyxl.workbook.external_link',
              'lib.python3.8.site-packages.openpyxl.packaging', 'lib.python3.8.site-packages.openpyxl.worksheet',
              'lib.python3.8.site-packages.openpyxl.chartsheet', 'lib.python3.8.site-packages.openpyxl.formatting',
              'lib.python3.8.site-packages.openpyxl.descriptors', 'lib.python3.8.site-packages.progress',
              'lib.python3.8.site-packages.psycopg2', 'lib.python3.8.site-packages.requests',
              'lib.python3.8.site-packages.sqlparse', 'lib.python3.8.site-packages.sqlparse.engine',
              'lib.python3.8.site-packages.sqlparse.filters', 'lib.python3.8.site-packages.jdatetime',
              'lib.python3.8.site-packages.packaging', 'lib.python3.8.site-packages.typed_ast',
              'lib.python3.8.site-packages.click_repl', 'lib.python3.8.site-packages.defusedxml',
              'lib.python3.8.site-packages.et_xmlfile', 'lib.python3.8.site-packages.et_xmlfile.tests',
              'lib.python3.8.site-packages.pyexcel_io', 'lib.python3.8.site-packages.pyexcel_io.readers',
              'lib.python3.8.site-packages.pyexcel_io.writers', 'lib.python3.8.site-packages.pyexcel_io.database',
              'lib.python3.8.site-packages.pyexcel_io.database.exporters',
              'lib.python3.8.site-packages.pyexcel_io.database.importers',
              'lib.python3.8.site-packages.pyexcel_io.plugin_api', 'lib.python3.8.site-packages.setuptools',
              'lib.python3.8.site-packages.setuptools.extern', 'lib.python3.8.site-packages.setuptools._vendor',
              'lib.python3.8.site-packages.setuptools._vendor.packaging',
              'lib.python3.8.site-packages.setuptools.command', 'lib.python3.8.site-packages.cachecontrol',
              'lib.python3.8.site-packages.cachecontrol.caches', 'lib.python3.8.site-packages.django_excel',
              'lib.python3.8.site-packages.webencodings', 'lib.python3.8.site-packages.click_plugins',
              'lib.python3.8.site-packages.import_export', 'lib.python3.8.site-packages.import_export.formats',
              'lib.python3.8.site-packages.import_export.templatetags', 'lib.python3.8.site-packages.pkg_resources',
              'lib.python3.8.site-packages.pkg_resources.extern', 'lib.python3.8.site-packages.pkg_resources._vendor',
              'lib.python3.8.site-packages.pkg_resources._vendor.packaging',
              'lib.python3.8.site-packages.pyexcel_webio', 'lib.python3.8.site-packages.django_filters',
              'lib.python3.8.site-packages.django_filters.rest_framework', 'lib.python3.8.site-packages.prompt_toolkit',
              'lib.python3.8.site-packages.prompt_toolkit.input', 'lib.python3.8.site-packages.prompt_toolkit.layout',
              'lib.python3.8.site-packages.prompt_toolkit.lexers', 'lib.python3.8.site-packages.prompt_toolkit.output',
              'lib.python3.8.site-packages.prompt_toolkit.styles', 'lib.python3.8.site-packages.prompt_toolkit.contrib',
              'lib.python3.8.site-packages.prompt_toolkit.contrib.ssh',
              'lib.python3.8.site-packages.prompt_toolkit.contrib.telnet',
              'lib.python3.8.site-packages.prompt_toolkit.contrib.completers',
              'lib.python3.8.site-packages.prompt_toolkit.contrib.regular_languages',
              'lib.python3.8.site-packages.prompt_toolkit.filters',
              'lib.python3.8.site-packages.prompt_toolkit.widgets',
              'lib.python3.8.site-packages.prompt_toolkit.clipboard',
              'lib.python3.8.site-packages.prompt_toolkit.eventloop',
              'lib.python3.8.site-packages.prompt_toolkit.shortcuts',
              'lib.python3.8.site-packages.prompt_toolkit.shortcuts.progress_bar',
              'lib.python3.8.site-packages.prompt_toolkit.completion',
              'lib.python3.8.site-packages.prompt_toolkit.application',
              'lib.python3.8.site-packages.prompt_toolkit.key_binding',
              'lib.python3.8.site-packages.prompt_toolkit.key_binding.bindings',
              'lib.python3.8.site-packages.prompt_toolkit.formatted_text', 'lib.python3.8.site-packages.rest_framework',
              'lib.python3.8.site-packages.rest_framework.utils', 'lib.python3.8.site-packages.rest_framework.schemas',
              'lib.python3.8.site-packages.rest_framework.authtoken',
              'lib.python3.8.site-packages.rest_framework.authtoken.management',
              'lib.python3.8.site-packages.rest_framework.authtoken.management.commands',
              'lib.python3.8.site-packages.rest_framework.authtoken.migrations',
              'lib.python3.8.site-packages.rest_framework.management',
              'lib.python3.8.site-packages.rest_framework.management.commands',
              'lib.python3.8.site-packages.rest_framework.templatetags', 'lib.python3.8.site-packages.click_didyoumean',
              'lib.python3.8.site-packages.diff_match_patch', 'lib.python3.8.site-packages.diff_match_patch.tests'],
    url='',
    license='',
    author='amir',
    author_email='amirbehvandi747@gmail.com',
    description='Automation for Training Company'
)
