# Generated by Django 4.0.1 on 2022-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
