# Generated by Django 4.0.1 on 2022-01-27 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_timesheet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='from_date',
            field=models.TimeField(default=datetime.datetime(2022, 1, 27, 9, 20, 0, 937762, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='to_date',
            field=models.TimeField(default=datetime.datetime(2022, 1, 27, 9, 20, 7, 913924, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
