# Generated by Django 4.0.1 on 2022-01-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_from_date_timesheet_from_temp_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='timesheet',
        #     name='from_date',
        # ),
        # migrations.RemoveField(
        #     model_name='timesheet',
        #     name='to_date',
        # ),
    ]
