# Generated by Django 4.0.1 on 2022-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_remove_timesheet_from_date_remove_timesheet_to_date'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='timesheet',
        #     name='from_date',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='timesheet',
        #     name='to_date',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
    ]
