# Generated by Django 4.0.1 on 2022-01-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_timesheet_from_date_timesheet_to_date'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='timesheet',
        #     name='from_date',
        # ),
        # migrations.RemoveField(
        #     model_name='timesheet',
        #     name='to_date',
        # ),
    ]
