# Generated by Django 4.0.6 on 2022-07-31 00:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('last_activity_ip', models.CharField(blank=True, max_length=30, null=True)),
                ('last_activity_date', models.DateTimeField(default=datetime.datetime(1950, 1, 1, 0, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
