# Generated by Django 4.0.6 on 2022-07-31 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0004_lastlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastlogin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_login_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
