# Generated by Django 3.2.5 on 2021-10-30 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0042_auto_20211015_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketNumber', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('department', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.CharField(blank=True, max_length=4092, null=True)),
                ('status', models.CharField(blank=True, choices=[('Done', 'Done'), ('OnProcess', 'OnProcess'), ('new', 'new')], max_length=10, null=True)),
                ('readFlag', models.BooleanField(blank=True, default=False, null=True)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('closeDate', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_asignedTO', to='training.tescandidate')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticke_can', to='training.tescandidate')),
            ],
        ),
    ]
