# Generated by Django 3.2.5 on 2021-10-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0042_auto_20211015_0816'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fileOne',
            field=models.FileField(blank=True, default=False, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fileTwo',
            field=models.FileField(blank=True, default=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_asignedTO', to='training.tescandidate'),
        ),
    ]
