# Generated by Django 3.2.5 on 2021-10-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0042_auto_20211015_0816'),
        ('ticket', '0003_alter_ticket_ticketnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('department', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.CharField(blank=True, max_length=4092, null=True)),
                ('status', models.CharField(blank=True, choices=[('Done', 'Done'), ('OnProcess', 'OnProcess'), ('new', 'new')], max_length=10, null=True)),
                ('readFlag', models.BooleanField(blank=True, default=False, null=True)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('fileOne', models.FileField(blank=True, default=False, null=True, upload_to='')),
                ('fileTwo', models.FileField(blank=True, default=False, null=True, upload_to='')),
                ('closeDate', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticke_answer', to='training.tescandidate')),
            ],
        ),
    ]
