# Generated by Django 3.2.5 on 2021-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticketanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketanswer',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.ManyToManyField(blank=True, null=True, to='ticket.TicketAnswer'),
        ),
    ]
