# Generated by Django 3.2.5 on 2021-10-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20211030_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanswer',
            name='fileOne',
            field=models.FileField(blank=True, null=True, upload_to='tickets'),
        ),
        migrations.AlterField(
            model_name='ticketanswer',
            name='fileTwo',
            field=models.FileField(blank=True, null=True, upload_to='tickets'),
        ),
    ]
