# Generated by Django 3.2.5 on 2021-11-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_asignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignedTo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
