# Generated by Django 4.0.6 on 2022-08-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticket_asignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closeDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
