# Generated by Django 4.0.6 on 2022-08-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0080_product_title'),
        ('staff', '0006_auto_20210420_1201'),
        ('ticket', '0013_ticket_new_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_asignedTO', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticke_can', to='training.tescandidate'),
        ),
    ]
