# Generated by Django 4.0.1 on 2022-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafftimesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
