# Generated by Django 4.0.1 on 2022-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafftimesheet', '0002_timesheet_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
