# Generated by Django 4.0.1 on 2022-03-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafftimesheet', '0003_timesheet_comment_alter_timesheet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='from_temp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
