# Generated by Django 4.0.1 on 2022-03-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafftimesheet', '0004_alter_timesheet_from_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='from_temp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
