# Generated by Django 4.0.1 on 2022-03-18 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stafftimesheet', '0006_timesheet_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_stafftimesheet', to=settings.AUTH_USER_MODEL),
        ),
    ]
