# Generated by Django 3.2 on 2021-04-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pclients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='PClinet',
        ),
    ]
