# Generated by Django 3.1.6 on 2021-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pclients', '0002_rename_student_pclinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pclinet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
