# Generated by Django 3.2 on 2021-04-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0018_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_doc', models.FileField(blank=True, null=True, upload_to='invoice_document')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='invoice_document')),
                ('amount', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('P', 'Partial Payment'), ('F', 'Fully Payment')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='can_invoice', to='training.candidateprofile')),
            ],
        ),
    ]
