# Generated by Django 3.2 on 2021-04-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='country',
            new_name='candidate',
        ),
    ]
