# Generated by Django 3.2 on 2021-04-27 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_country_invoice_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='balance',
        ),
    ]
