# Generated by Django 3.2 on 2021-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
