# Generated by Django 3.2 on 2021-04-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_temp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table=None,
        ),
    ]
