# Generated by Django 4.0.4 on 2022-05-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='company_address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='company_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='contact_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='email',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='fax',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='phone',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='post_code',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
