# Generated by Django 4.0.4 on 2022-05-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_eventcandidatepayment_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='sponsor_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
