# Generated by Django 4.0.4 on 2022-05-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_eventcandidatepayment_sponsor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
