# Generated by Django 4.0.4 on 2022-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_eventcandidatepayment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcandidatepayment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
