# Generated by Django 4.0.4 on 2022-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_alter_eventcandidatepayment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='invoiced_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_file'),
        ),
        migrations.AddField(
            model_name='eventcandidatepayment',
            name='recipients_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_file'),
        ),
    ]
