# Generated by Django 4.0.4 on 2022-07-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0080_product_title'),
        ('financials', '0006_eventcandidatepayment_invoiced_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcandidatepayment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_payment', to='training.event'),
        ),
    ]
