# Generated by Django 4.0.1 on 2022-04-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0003_timeflightdiffractiontofdlevel3_cswip_material_basic_a3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeflightdiffractiontofdlevel3_cswip_material',
            name='basic_a3',
        ),
    ]
