# Generated by Django 4.0.1 on 2022-04-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0004_remove_timeflightdiffractiontofdlevel3_cswip_material_basic_a3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFlightDiffractionTOFDLevel3_CSWIP_Material2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('basic_a1', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_a2', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_1', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_2', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_3', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_4', models.CharField(blank=True, max_length=256, null=True)),
                ('main_c_1', models.CharField(blank=True, max_length=256, null=True)),
                ('main_c_2', models.CharField(blank=True, max_length=256, null=True)),
                ('main_c_3', models.CharField(blank=True, max_length=256, null=True)),
                ('practical_tofd_l2', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cswip_material_phased_Array_l3_candidate2', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cswip_material_phased_Array_l3_event2', to='training.event')),
            ],
        ),
    ]
