# Generated by Django 4.0.1 on 2022-03-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0070_event_exam_att_file_event_traning_att_file'),
        ('exam_certification', '0005_alter_certificate_name_alter_certificatetype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('authorized_signatory', models.CharField(blank=True, max_length=256, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=256, null=True)),
                ('course_duration', models.IntegerField(blank=True, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_event', to='training.event')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invigilator_exam', to='exam_certification.invigilator')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_type', to='exam_certification.certificatetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
