# Generated by Django 4.0.1 on 2022-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0006_certificateattendance_delete_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateattendance',
            name='cer_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
