# Generated by Django 4.0.1 on 2022-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0007_alter_phasedarrayultrasonictesting_paut_l3_pcn_material_basic_a1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='basic_a1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='basic_a2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='basic_b_part_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='basic_b_part_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='basic_b_part_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='basic_b_part_4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='main_d',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='main_e',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='main_f',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material',
            name='practical_tofd_l2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
