# Generated by Django 4.0.1 on 2022-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0009_timeflightdiffractiontofdlevel3_pcn_material2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='macro_paper',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='pipe_paper',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='plate_paper',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
