# Generated by Django 4.0.1 on 2022-04-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0010_alter_cswipweldinginspector3_1exammaterial_macro_paper_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeflightdiffractiontofdlevel3_pcn_material2',
            old_name='scheme',
            new_name='exam_title',
        ),
    ]
