# Generated by Django 4.0.1 on 2022-03-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0010_cswipcertificateproduct_pcncertificateproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cswipcertificateattendance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cswip_exam_product', to='exam_certification.cswipcertificateproduct'),
        ),
        migrations.AddField(
            model_name='pcncertificateattendance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcn_exam_product', to='exam_certification.pcncertificateproduct'),
        ),
    ]
