# Generated by Django 4.0.1 on 2022-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0011_rename_scheme_timeflightdiffractiontofdlevel3_pcn_material2_exam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cswipweldinginspector3_2_1exammaterial',
            name='general_theory_s',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_2_1exammaterial',
            name='ndt_s',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_2_1exammaterial',
            name='scenario_s',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_2_1exammaterial',
            name='symbols_s',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
