# Generated by Django 4.0.1 on 2022-04-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0012_exammaterialpiwiattendance_exammaterialpiwi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammaterialpiwi',
            name='attendance',
        ),
        migrations.AddField(
            model_name='exammaterialpiwi',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pi_candidate', to='training.tescandidate'),
        ),
        migrations.AddField(
            model_name='exammaterialpiwi',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exammaterialpiwi',
            name='exam_revision',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='exammaterialpiwi',
            name='invigilator',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='exammaterialpiwi',
            name='lecturer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='exammaterialpiwi',
            name='remark',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.DeleteModel(
            name='ExamMaterialPiWiAttendance',
        ),
    ]
