# Generated by Django 4.0.1 on 2022-04-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0013_remove_exammaterialpiwi_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammaterialpiwi',
            name='customerID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
