# Generated by Django 4.0.1 on 2022-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0014_alter_cswipweldinginspector3_2_2exammaterial_general_theory_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgas_cswip_paintinginspectormaterial',
            name='general_theory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bgas_cswip_paintinginspectormaterial',
            name='practical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
