# Generated by Django 4.0.4 on 2022-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0015_alter_bgas_cswip_paintinginspectormaterial_general_theory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiographicinterpretationweldsrimaterial',
            name='general_theory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='radiographicinterpretationweldsrimaterial',
            name='practical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='radiographicinterpretationweldsrimaterial',
            name='specific_theory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
