# Generated by Django 4.0.4 on 2022-04-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0016_alter_radiographicinterpretationweldsrimaterial_general_theory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalRadiographicInterpretationDRI_Level2_Material3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, max_length=256, null=True)),
                ('general_practical', models.CharField(blank=True, max_length=256, null=True)),
                ('data_analysis1', models.CharField(blank=True, max_length=256, null=True)),
                ('data_analysis2', models.CharField(blank=True, max_length=256, null=True)),
                ('data_analysis3', models.CharField(blank=True, max_length=256, null=True)),
                ('data_analysis4', models.CharField(blank=True, max_length=256, null=True)),
                ('data_analysis5', models.CharField(blank=True, max_length=256, null=True)),
                ('data_analysis6', models.CharField(blank=True, max_length=256, null=True)),
                ('general_theory', models.CharField(blank=True, max_length=256, null=True)),
                ('specific_theory', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dri_candidate13', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dri_event13', to='training.event')),
            ],
        ),
    ]
