# Generated by Django 4.0.1 on 2022-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0017_exammaterialtofdmodel1_delete_exammaterialtofdmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammaterialtofdmodel1',
            name='exam_revision',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
