# Generated by Django 4.0.4 on 2022-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0019_phasedarrayultrasonictesting_paut_l3_pcn_material_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeflightdiffractiontofdlevel3_cswip_material',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='timeflightdiffractiontofdlevel3_cswip_result',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
