# Generated by Django 4.0.1 on 2022-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0020_exammateriall3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_basic_a1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_basic_a2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_basic_b_part_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_basic_b_part_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_basic_b_part_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_basic_b_part_4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_delivery_method',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_exam_date',
            field=models.DateTimeField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_main_c_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_main_c_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_main_c_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_ndtl3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_pautl2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammateriall3',
            name='paut_practical_exam',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
