# Generated by Django 4.0.4 on 2022-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0021_timeflightdiffractiontofdlevel3_pcn_result3'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiographicinterpretationweldsrimaterial',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
