# Generated by Django 4.0.1 on 2022-04-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0023_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaterialTofdL3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_exam_date', models.DateTimeField(blank=True, null=True)),
                ('tofd_ndtl3', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_pautl2', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_practical_exam', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_basic_a1', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_basic_a2', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_basic_b_part_1', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_basic_b_part_2', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_basic_b_part_3', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_basic_b_part_4', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_main_c_1', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_main_c_2', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_main_c_3', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_venue', models.CharField(blank=True, max_length=256, null=True)),
                ('tofd_remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('pcn_tofd_l3_scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_exam_date', models.DateTimeField(blank=True, null=True)),
                ('pcn_tofd_l3_ndtl3', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_pautl2', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_practical_exam', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_basic_a1', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_basic_a2', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_basic_b_part_1', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_basic_b_part_2', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_basic_b_part_3', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_basic_b_part_4', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_main_d', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_main_e', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_main_f', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_venue', models.CharField(blank=True, max_length=256, null=True)),
                ('pcn_tofd_l3_remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_tofd_l3_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_tofd_l3_event', to='training.event')),
            ],
        ),
    ]
