# Generated by Django 4.0.4 on 2022-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0023_digitalradiographicinterpretationdri_level2_result_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalradiographicinterpretationdri_level2_material3',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
