# Generated by Django 4.0.4 on 2022-04-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0024_digitalradiographicinterpretationdri_level2_material3_exam_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaterialTOFD_CSWIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('cswip_pcn', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_title', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('general_theory', models.CharField(blank=True, max_length=256, null=True)),
                ('specific_theory', models.CharField(blank=True, max_length=256, null=True)),
                ('sample1', models.CharField(blank=True, max_length=256, null=True)),
                ('sample2', models.CharField(blank=True, max_length=256, null=True)),
                ('data_file_1', models.CharField(blank=True, max_length=256, null=True)),
                ('data_file_2', models.CharField(blank=True, max_length=256, null=True)),
                ('data_file_3', models.CharField(blank=True, max_length=256, null=True)),
                ('data_file_4', models.CharField(blank=True, max_length=256, null=True)),
                ('data_file_5', models.CharField(blank=True, max_length=256, null=True)),
                ('written_instruction', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_tofd_l2_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_tofd_l2_event', to='training.event')),
            ],
        ),
    ]
