# Generated by Django 4.0.1 on 2022-04-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0025_remove_exammateriall3_pcn_tofd_l3_basic_a1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultPautL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('explanation', models.CharField(blank=True, max_length=4096, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_result_file')),
                ('general_theory', models.FloatField(blank=True, null=True)),
                ('specific_theory', models.FloatField(blank=True, null=True)),
                ('sample1_analysis', models.FloatField(blank=True, null=True)),
                ('sample1_collection', models.FloatField(blank=True, null=True)),
                ('sample2_analysis', models.FloatField(blank=True, null=True)),
                ('sample2_collection', models.FloatField(blank=True, null=True)),
                ('sample3_analysis', models.FloatField(blank=True, null=True)),
                ('sample3_collection', models.FloatField(blank=True, null=True)),
                ('written_instruction', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_event', to='training.event')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result', to='exam_certification.exammaterialpautl2')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
