# Generated by Django 4.0.1 on 2022-04-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0026_examresultpautl2_delete_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresultpautl2',
            name='cswip_pcn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
