# Generated by Django 4.0.1 on 2022-04-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0027_examresultpautl2_cswip_pcn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammaterialtofdmodel1',
            name='exam_revision',
        ),
        migrations.AddField(
            model_name='exammaterialtofdmodel1',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
