# Generated by Django 4.0.4 on 2022-04-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0028_alter_cswipweldinginspector3_1result_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cswipweldinginspector3_1result',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cswipweldinginspector3_1result',
            name='exam_titme',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
