# Generated by Django 4.0.1 on 2022-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0028_remove_exammaterialtofdmodel1_exam_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammaterialpautl2',
            name='exam_revision',
        ),
        migrations.AddField(
            model_name='exammaterialpautl2',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
