# Generated by Django 4.0.1 on 2022-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0029_remove_exammaterialpautl2_exam_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresultpautl2',
            name='general_theory',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='sample1_analysis',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='sample1_collection',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='sample2_analysis',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='sample2_collection',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='sample3_analysis',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='sample3_collection',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='specific_theory',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='examresultpautl2',
            name='written_instruction',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
