# Generated by Django 4.0.4 on 2022-04-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0030_remove_cswipweldinginspector3_1result_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cswipweldinginspector3_1result',
            old_name='exam_titme',
            new_name='exam_title',
        ),
    ]
