# Generated by Django 4.0.1 on 2022-04-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0030_alter_examresultpautl2_general_theory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSWIPWeldingInspector3_1ExamMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('explanation', models.CharField(blank=True, max_length=4096, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_result_file')),
                ('general_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('technology_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('plate_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('pipe_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('macro_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_candidate_31_exam_material', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_event_31_exam_material', to='training.event')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_31_exam_material', to='exam_certification.exammaterialpautl2')),
            ],
        ),
        migrations.CreateModel(
            name='CSWIPWeldingInspector3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('explanation', models.CharField(blank=True, max_length=4096, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_result_file')),
                ('general_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('technology_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('plate_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('pipe_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('macro_paper', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_candidate_31', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_event_31', to='training.event')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_31', to='exam_certification.cswipweldinginspector3_1exammaterial')),
            ],
        ),
    ]
