# Generated by Django 4.0.4 on 2022-04-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0031_rename_exam_titme_cswipweldinginspector3_1result_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiographicinterpretationweldsriresult',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
