# Generated by Django 4.0.1 on 2022-04-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0033_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammaterialpautl2',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample', to='exam_certification.samples'),
        ),
    ]
