# Generated by Django 4.0.1 on 2022-04-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0034_exammaterialpautl2_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='general_theory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_general_theory', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='sample1_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_sample1_analysis', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='sample1_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_sample1_collection', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='sample2_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_sample2_analysis', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='sample2_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_gsample2_collection', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='sample3_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_sample3_analysis', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='sample3_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_sample3_collection', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='specific_theory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_specific_theory', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='written_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_written_instruction', to='exam_certification.samples'),
        ),
    ]
