# Generated by Django 4.0.4 on 2022-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0035_phasedarrayultrasonictesting_paut_l3cswipmaterial_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipresult',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
