# Generated by Django 4.0.1 on 2022-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0035_alter_exammaterialpautl2_general_theory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='written_instruction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
