# Generated by Django 4.0.1 on 2022-04-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0036_alter_exammaterialpautl2_written_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='general_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_31_sample_general_paper', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='macro_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_31_sample_macro_paper', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='pipe_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_31_sample_pipe_paper', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='plate_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_31_sample_plate_paper', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='technology_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_31_sample_technology_paper', to='exam_certification.samples'),
        ),
    ]
