# Generated by Django 4.0.4 on 2022-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0036_phasedarrayultrasonictesting_paut_l3cswipresult_exam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialtofdmodel1',
            name='data_file_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialtofdmodel1',
            name='data_file_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialtofdmodel1',
            name='data_file_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialtofdmodel1',
            name='data_file_4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialtofdmodel1',
            name='data_file_5',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
