# Generated by Django 4.0.4 on 2022-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0037_alter_exammaterialtofdmodel1_data_file_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialphasedarrayultrasonictesting_tofd_level2pcn',
            name='sample1_analysis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialphasedarrayultrasonictesting_tofd_level2pcn',
            name='sample2_analysis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialphasedarrayultrasonictesting_tofd_level2pcn',
            name='sample3_analysis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialphasedarrayultrasonictesting_tofd_level2pcn',
            name='sample4_analysis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exammaterialphasedarrayultrasonictesting_tofd_level2pcn',
            name='sample5_analysis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
