# Generated by Django 4.0.1 on 2022-04-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0037_alter_cswipweldinginspector3_1exammaterial_general_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
