# Generated by Django 4.0.1 on 2022-04-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0039_cswipweldinginspector3_1exammaterial_customerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='exam_title',
        ),
        migrations.RemoveField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='invigilator',
        ),
        migrations.RemoveField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='lecturer',
        ),
    ]
