# Generated by Django 4.0.1 on 2022-04-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0040_remove_cswipweldinginspector3_1exammaterial_customerid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cswipweldinginspector3_1exammaterial',
            old_name='explanation',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='cswipweldinginspector3_1result',
            old_name='explanation',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='cswip_pcn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='customerID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='exam_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='invigilator',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cswipweldinginspector3_1exammaterial',
            name='lecturer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
