# Generated by Django 4.0.4 on 2022-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0042_cswipweldinginspector3_2_1exammaterial2_plant_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='cswipweldinginspector3_2_1exammaterial',
            name='plant_paper',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
