# Generated by Django 4.0.1 on 2022-04-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0044_alter_exammaterialpautl2_written_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='written_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_pautl_sample_written', to='exam_certification.samples'),
        ),
    ]
