# Generated by Django 4.0.1 on 2022-04-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0045_alter_exammaterialpautl2_written_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cswipweldinginspector3_1resultintermadiate',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_31_intermediate', to='exam_certification.cswipweldinginspector3_1result'),
        ),
    ]
