# Generated by Django 4.0.4 on 2022-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0047_cswipweldinginspector3_2_2_result_inter_group_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiographicinterpretationweldsriresult',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='exam_file'),
        ),
    ]
