# Generated by Django 4.0.4 on 2022-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0048_radiographicinterpretationweldsriresult_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cswipweldinginspector3_1result',
            name='overall',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
