# Generated by Django 4.0.1 on 2022-04-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0049_rename_result_cswipweldinginspector3_1resultintermadiate_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cswipweldinginspector3_1resultintermadiate',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_result_intermadiate_candidate', to='training.tescandidate'),
        ),
    ]
