# Generated by Django 4.0.4 on 2022-07-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0080_product_title'),
        ('exam_certification', '0050_bgas_cswip_paintinginspectorresult_overall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialpautl2',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_material_pautl_event', to='training.event'),
        ),
    ]
