# Generated by Django 4.0.6 on 2022-08-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0052_pcncertificateattendance_exam_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcncertificateattendance',
            name='exam_title',
        ),
    ]
