# Generated by Django 4.0.1 on 2022-04-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0053_cswipweldinginspector3_2_2exammaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGAS_CSWIP_PaintingInspectorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_title', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('remarks', models.CharField(blank=True, max_length=4096, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_result_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_candidate_painting_exam_result', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_event_painting_exam_result', to='training.event')),
                ('general_theory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_painting_general_result', to='exam_certification.samples')),
                ('practical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_painting_sample_technology_result', to='exam_certification.samples')),
            ],
        ),
        migrations.CreateModel(
            name='BGAS_CSWIP_PaintingInspectorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_title', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('remarks', models.CharField(blank=True, max_length=4096, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_result_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_candidate_painting_exam_material', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_result_event_painting_exam_material', to='training.event')),
                ('general_theory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_painting_general_paper', to='exam_certification.samples')),
                ('practical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_painting_sample_technology_paper', to='exam_certification.samples')),
            ],
        ),
    ]
