# Generated by Django 4.0.1 on 2022-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0054_bgas_cswip_paintinginspectorresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgas_cswip_paintinginspectorresult',
            name='general_theory',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bgas_cswip_paintinginspectorresult',
            name='practical',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
