# Generated by Django 4.0.1 on 2022-04-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0056_exammaterialphasedarrayultrasonictesting_paut_level2cswip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaterialPhasedArrayUltrasonicTesting_PAUT_Level2PCN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('cswip_pcn', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_title', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultra_candidate_pcn', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultra_event_pcn', to='training.event')),
                ('general_theory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_general_theory_pcn', to='exam_certification.samples')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultra_sample_pcn', to='exam_certification.samples')),
                ('sample1_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_sample1_analysis_pcn', to='exam_certification.samples')),
                ('sample1_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_sample1_collection_pcn', to='exam_certification.samples')),
                ('sample2_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_sample2_analysis_pcn', to='exam_certification.samples')),
                ('sample2_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_gsample2_collection_pcn', to='exam_certification.samples')),
                ('sample3_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_sample3_analysis_pcn', to='exam_certification.samples')),
                ('sample3_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_sample3_collection_pcn', to='exam_certification.samples')),
                ('specific_theory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_specific_theory_pcn', to='exam_certification.samples')),
                ('written_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_written_pcn', to='exam_certification.samples')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Result_PhasedArrayUltrasonicTesting_PAUT_Level2PCN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('cswip_pcn', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_title', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('general_theory', models.CharField(blank=True, max_length=128, null=True)),
                ('specific_theory', models.CharField(blank=True, max_length=128, null=True)),
                ('sample1_analysis', models.CharField(blank=True, max_length=128, null=True)),
                ('sample1_collection', models.CharField(blank=True, max_length=128, null=True)),
                ('sample2_analysis', models.CharField(blank=True, max_length=128, null=True)),
                ('sample2_collection', models.CharField(blank=True, max_length=128, null=True)),
                ('sample3_analysis', models.CharField(blank=True, max_length=128, null=True)),
                ('sample3_collection', models.CharField(blank=True, max_length=128, null=True)),
                ('written_instruction', models.CharField(blank=True, max_length=128, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultra_result_candidate_pcn', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultra_result_event_pcn', to='training.event')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultra_result_sample_pcn', to='exam_certification.samples')),
            ],
        ),
    ]
