# Generated by Django 4.0.1 on 2022-04-17 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0059_phasedarrayultrasonictesting_paut_l3cswipresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 17, 18, 20, 46, 383959)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 17, 18, 20, 55, 184252)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
