# Generated by Django 4.0.1 on 2022-04-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0060_phasedarrayultrasonictesting_paut_l3cswipmaterial_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='practical_paut_l2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_practical_paut', to='exam_certification.samples'),
        ),
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipresult',
            name='practical_paut_l2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
