# Generated by Django 4.0.1 on 2022-04-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0061_phasedarrayultrasonictesting_paut_l3cswipmaterial_practical_paut_l2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='basic_a1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_b1_theory_paut_pcn', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='basic_a2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_a2_paut_pcn', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='basic_b_part_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b1_paut_pcn', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='basic_b_part_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b2_paut_pcn', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='basic_b_part_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b3_paut_pcn', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='basic_b_part_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b4_paut_pcn', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcn_material_phased_Array_l3_candidate', to='training.tescandidate'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcn_material_phased_Array_l3_event', to='training.event'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='main_c_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_d_paut', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='main_c_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_e_paut', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='main_c_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_f_paut', to='exam_certification.samples'),
        ),
        migrations.AlterField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='practical_paut_l2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_practical_paut_pcn', to='exam_certification.samples'),
        ),
        migrations.CreateModel(
            name='PhasedArrayUltrasonicTesting_PAUT_L3_PCN_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, max_length=256, null=True)),
                ('basic_a1', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_a2', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_1', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_2', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_3', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_b_part_4', models.CharField(blank=True, max_length=256, null=True)),
                ('main_d', models.CharField(blank=True, max_length=256, null=True)),
                ('main_e', models.CharField(blank=True, max_length=256, null=True)),
                ('main_f', models.CharField(blank=True, max_length=256, null=True)),
                ('practical_paut_l2', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcn_material_phased_Array_l3_candidate_result', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcn_material_phased_Array_l3_event_result', to='training.event')),
            ],
        ),
        migrations.CreateModel(
            name='PhasedArrayUltrasonicTesting_PAUT_L3_PCN_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, max_length=256, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_a1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_b1_theory_paut', to='exam_certification.samples')),
                ('basic_a2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_a2_paut', to='exam_certification.samples')),
                ('basic_b_part_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b1_paut', to='exam_certification.samples')),
                ('basic_b_part_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b2_paut', to='exam_certification.samples')),
                ('basic_b_part_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b3_paut', to='exam_certification.samples')),
                ('basic_b_part_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_b4_paut', to='exam_certification.samples')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_phased_Array_l3_candidate', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_phased_Array_l3_event', to='training.event')),
                ('main_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_c1_paut', to='exam_certification.samples')),
                ('main_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_c2_paut', to='exam_certification.samples')),
                ('main_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_sample_c3_paut', to='exam_certification.samples')),
                ('practical_paut_l2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ultera_practical_paut', to='exam_certification.samples')),
            ],
        ),
    ]
