# Generated by Django 4.0.1 on 2022-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0062_alter_phasedarrayultrasonictesting_paut_l3cswipmaterial_basic_a1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3_pcn_material',
            name='customerID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3_pcn_result',
            name='customerID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipmaterial',
            name='customerID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='phasedarrayultrasonictesting_paut_l3cswipresult',
            name='customerID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
