# Generated by Django 4.0.1 on 2022-04-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0064_timeflightdiffractiontofdlevel3_cswip_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeflightdiffractiontofdlevel3_cswip_material',
            old_name='practical_paut_l2',
            new_name='practical_tofd_l2',
        ),
        migrations.RenameField(
            model_name='timeflightdiffractiontofdlevel3_cswip_result',
            old_name='practical_paut_l2',
            new_name='practical_tofd_l2',
        ),
    ]
