# Generated by Django 4.0.1 on 2022-04-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_event_end_exam_date_event_start_exam_date'),
        ('exam_certification', '0066_timeflightdiffractiontofdlevel3_pcn_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiographicInterpretationWeldsRIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, max_length=256, null=True)),
                ('general_theory', models.CharField(blank=True, max_length=256, null=True)),
                ('specific_theory', models.CharField(blank=True, max_length=256, null=True)),
                ('practical', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ri_candidate1_result', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ri_event1_result', to='training.event')),
            ],
        ),
        migrations.CreateModel(
            name='RadiographicInterpretationWeldsRIMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('customerID', models.CharField(blank=True, max_length=256, null=True)),
                ('scheme', models.CharField(blank=True, max_length=256, null=True)),
                ('exam_date', models.DateTimeField(blank=True, max_length=256, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=256, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=256, null=True)),
                ('invigilator', models.CharField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ri_candidate1', to='training.tescandidate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ri_event1', to='training.event')),
                ('general_theory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ri', to='exam_certification.samples')),
                ('practical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_ri_practical', to='exam_certification.samples')),
                ('specific_theory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_specific_ri', to='exam_certification.samples')),
            ],
        ),
    ]
