# Generated by Django 4.0.1 on 2022-04-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0071_alter_exammaterialtofdmodel1_data_file_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialtofdmodel1',
            name='written_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_material_written_instruction', to='exam_certification.samples'),
        ),
    ]
