# Generated by Django 4.0.1 on 2022-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0073_alter_exammaterialtofdmodel1_written_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammaterialtofdmodel1',
            name='written_instruction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
