# Generated by Django 4.0.1 on 2022-04-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_certification', '0075_alter_exammaterialtofdmodel1_written_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammaterialphasedarrayultrasonictesting_paut_level2pcn',
            name='general_theory',
        ),
        migrations.AddField(
            model_name='exammaterialphasedarrayultrasonictesting_paut_level2pcn',
            name='specific_theory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
